/**
 * agents.test.ts — `lore agents` (LORE-36): the SKILL.md + CLAUDE.md-nudge agent bridge.
 *
 * The two acceptance criteria are exercised directly:
 *   AC#1 — re-running makes no changes (idempotent): a second run reports `unchanged` and touches
 *          zero bytes; `--check` on a current bridge exits 0, on a stale one exits 6.
 *   AC#2 — SKILL.md stays small and points at `lore instructions`.
 *
 * Plus the bridge's load-bearing guarantees: the CLAUDE.md nudge is a managed block that never
 * clobbers surrounding prose or an unrelated block; `--force` overwrites a differing (hand-edited)
 * SKILL.md while the default leaves it `protected`; and — guarding the exact LORE-37 failure mode —
 * the generated content names only commands the real dispatcher actually handles.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { run } from "../src/cli";
import { type AgentsResult, runAgents } from "../src/commands/agents";
import {
  buildNudgeBody,
  buildSkillDoc,
  CLAUDE_MD_REL_PATH,
  LORE_COMMANDS,
  planBridge,
  SKILL_REL_PATH,
} from "../src/core/agent-bridge";
import { LoreError } from "../src/errors";
import type { OutputContext } from "../src/output";
import { capture } from "./helpers";

const JSON_CTX: OutputContext = { mode: "json", color: false };
const PLAIN_CTX: OutputContext = { mode: "plain", color: false };

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "lore-agents-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Run `agents` in JSON mode and return the parsed `data` payload plus the exit code. */
function agents(args: string[] = []): { code: number; result: AgentsResult } {
  const stdout = capture();
  const code = runAgents({ root, output: JSON_CTX, args, stdout });
  const envelope = JSON.parse(stdout.text()) as { kind: string; data: AgentsResult };
  expect(envelope.kind).toBe("agents.result");
  return { code, result: envelope.data };
}

/** The action recorded for a given repo-relative path in a result. */
function actionFor(result: AgentsResult, path: string): string | undefined {
  return result.files.find((file) => file.path === path)?.action;
}

const skillAbs = (): string => join(root, SKILL_REL_PATH);
const claudeAbs = (): string => join(root, CLAUDE_MD_REL_PATH);

describe("generated content (AC#2) — small, grounded, points at `lore instructions`", () => {
  test("buildSkillDoc is deterministic (timestamp-free) so re-generation is byte-identical", () => {
    expect(buildSkillDoc()).toBe(buildSkillDoc());
  });

  test("SKILL.md carries the skill frontmatter and points the agent at `lore instructions`", () => {
    const skill = buildSkillDoc();
    expect(skill.startsWith("---\nname: lore\n")).toBe(true);
    expect(skill).toContain("lore instructions");
    expect(skill).toContain("source of truth");
  });

  test("the CLAUDE.md nudge points at both the skill and `lore instructions`", () => {
    const nudge = buildNudgeBody();
    expect(nudge).toContain(SKILL_REL_PATH);
    expect(nudge).toContain("lore instructions");
  });

  test("generated content names every real command and NOTHING unshipped (the LORE-37 trap)", () => {
    const skill = buildSkillDoc();
    for (const cmd of LORE_COMMANDS) {
      expect(skill).toContain(`\`${cmd.name}\``);
    }
    // The bridge must never teach a command the router does not dispatch (the LORE-37 phantom trap).
    const shipped = new Set(LORE_COMMANDS.map((c) => c.name));
    for (const phantom of ["obsidian-scaffold-does-not-exist"]) {
      expect(shipped.has(phantom)).toBe(false);
      expect(skill).not.toContain(`\`${phantom}\``);
    }
  });
});

describe("planBridge (pure) — write disciplines", () => {
  test("a fresh repo plans to create both files with their generated bytes", () => {
    const plan = planBridge({ skillOnDisk: null, claudeOnDisk: null, force: false });
    const skill = plan.files.find((f) => f.path === SKILL_REL_PATH);
    const claude = plan.files.find((f) => f.path === CLAUDE_MD_REL_PATH);
    expect(skill?.action).toBe("created");
    expect(skill?.contents).toBe(buildSkillDoc());
    expect(claude?.action).toBe("created");
    expect(claude?.contents).toContain("<!-- lore:agents:begin -->");
  });

  test("applying the plan then re-planning yields `unchanged` for both (idempotent)", () => {
    const first = planBridge({ skillOnDisk: null, claudeOnDisk: null, force: false });
    const skillBytes = first.files.find((f) => f.path === SKILL_REL_PATH)?.contents ?? null;
    const claudeBytes = first.files.find((f) => f.path === CLAUDE_MD_REL_PATH)?.contents ?? null;
    const second = planBridge({ skillOnDisk: skillBytes, claudeOnDisk: claudeBytes, force: false });
    expect(second.files.every((f) => f.action === "unchanged")).toBe(true);
    expect(second.files.every((f) => f.contents === null)).toBe(true);
  });

  test("a differing SKILL.md is `protected` without --force and `updated` with it", () => {
    const edited = `${buildSkillDoc()}\nhand edit`;
    const withoutForce = planBridge({ skillOnDisk: edited, claudeOnDisk: null, force: false });
    expect(withoutForce.files.find((f) => f.path === SKILL_REL_PATH)?.action).toBe("protected");
    expect(withoutForce.files.find((f) => f.path === SKILL_REL_PATH)?.contents).toBeNull();

    const withForce = planBridge({ skillOnDisk: edited, claudeOnDisk: null, force: true });
    expect(withForce.files.find((f) => f.path === SKILL_REL_PATH)?.action).toBe("updated");
    expect(withForce.files.find((f) => f.path === SKILL_REL_PATH)?.contents).toBe(buildSkillDoc());
  });
});

describe("lore agents — fresh generation (AC#1)", () => {
  test("creates both bridge files and exits 0", () => {
    const { code, result } = agents();
    expect(code).toBe(0);
    expect(actionFor(result, SKILL_REL_PATH)).toBe("created");
    expect(actionFor(result, CLAUDE_MD_REL_PATH)).toBe("created");
    expect(readFileSync(skillAbs(), "utf8")).toBe(buildSkillDoc());
    expect(readFileSync(claudeAbs(), "utf8")).toContain("<!-- lore:agents:begin -->");
  });
});

describe("lore agents — idempotent re-run (AC#1)", () => {
  test("a second run reports `unchanged` for both and touches zero bytes", () => {
    agents();
    const skillBefore = readFileSync(skillAbs(), "utf8");
    const claudeBefore = readFileSync(claudeAbs(), "utf8");

    const { code, result } = agents();
    expect(code).toBe(0);
    expect(actionFor(result, SKILL_REL_PATH)).toBe("unchanged");
    expect(actionFor(result, CLAUDE_MD_REL_PATH)).toBe("unchanged");
    expect(readFileSync(skillAbs(), "utf8")).toBe(skillBefore);
    expect(readFileSync(claudeAbs(), "utf8")).toBe(claudeBefore);
  });
});

describe("lore agents — --check (the CI drift gate)", () => {
  test("exits 0 on a current bridge and writes nothing", () => {
    agents();
    const skillBefore = readFileSync(skillAbs(), "utf8");
    const { code } = agents(["--check"]);
    expect(code).toBe(0);
    expect(readFileSync(skillAbs(), "utf8")).toBe(skillBefore);
  });

  test("exits 6 on a stale bridge and still writes nothing", () => {
    agents();
    const stale = `${buildSkillDoc()}\ndrifted`;
    writeFileSync(skillAbs(), stale);
    const { code } = agents(["--check"]);
    expect(code).toBe(6);
    // A --check run must not repair the drift it reports.
    expect(readFileSync(skillAbs(), "utf8")).toBe(stale);
  });

  test("exits 6 when a bridge file is missing entirely", () => {
    agents();
    rmSync(skillAbs());
    expect(agents(["--check"]).code).toBe(6);
  });

  test("does not force the plan: a hand-edited SKILL.md is `protected` (consistent with force:false), not `updated`", () => {
    // Regression: forcing the plan under --check reported action `updated` alongside force:false and
    // printed an inert "run `lore agents`" remedy that leaves the file protected (permanently-red CI).
    agents();
    writeFileSync(skillAbs(), `${buildSkillDoc()}\nhand edit`);
    const { code, result } = agents(["--check"]);
    expect(code).toBe(6);
    expect(result.force).toBe(false);
    expect(actionFor(result, SKILL_REL_PATH)).toBe("protected");
  });
});

describe("lore agents — --force vs. the default protection", () => {
  test("a hand-edited SKILL.md is left untouched by default (protected) and overwritten by --force", () => {
    agents();
    const handEdited = `${buildSkillDoc()}\nmy customization`;
    writeFileSync(skillAbs(), handEdited);

    const def = agents();
    expect(def.code).toBe(0);
    expect(actionFor(def.result, SKILL_REL_PATH)).toBe("protected");
    expect(readFileSync(skillAbs(), "utf8")).toBe(handEdited);

    const forced = agents(["--force"]);
    expect(forced.code).toBe(0);
    expect(actionFor(forced.result, SKILL_REL_PATH)).toBe("updated");
    expect(readFileSync(skillAbs(), "utf8")).toBe(buildSkillDoc());
  });
});

describe("lore agents — CLAUDE.md nudge is a non-clobbering managed block", () => {
  test("inserts the lore block into an existing CLAUDE.md, preserving an unrelated block and prose", () => {
    const existing = [
      "# Project memory",
      "",
      "<!-- BACKLOG.MD GUIDELINES START -->",
      "Use the backlog CLI.",
      "<!-- BACKLOG.MD GUIDELINES END -->",
      "",
      "Hand-authored prose.",
      "",
    ].join("\n");
    writeFileSync(claudeAbs(), existing);

    const { result } = agents();
    expect(actionFor(result, CLAUDE_MD_REL_PATH)).toBe("updated");
    const after = readFileSync(claudeAbs(), "utf8");
    expect(after).toContain(
      "<!-- BACKLOG.MD GUIDELINES START -->\nUse the backlog CLI.\n<!-- BACKLOG.MD GUIDELINES END -->",
    );
    expect(after).toContain("Hand-authored prose.");
    expect(after).toContain("<!-- lore:agents:begin -->");
    // And it is idempotent from this seeded state.
    expect(agents().result.files.find((f) => f.path === CLAUDE_MD_REL_PATH)?.action).toBe("unchanged");
  });

  test("a malformed lore:agents marker pair in CLAUDE.md is a fail-loud validation error (exit 6)", () => {
    writeFileSync(claudeAbs(), "<!-- lore:agents:begin -->\nx\n<!-- lore:agents:begin -->\n<!-- lore:agents:end -->\n");
    let thrown: unknown;
    try {
      runAgents({ root, output: JSON_CTX, args: [], stdout: capture() });
    } catch (err) {
      thrown = err;
    }
    expect(thrown).toBeInstanceOf(LoreError);
    expect((thrown as LoreError).type).toBe("validation");
  });
});

describe("lore agents — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file", () => {
    const stdout = capture();
    runAgents({ root, output: PLAIN_CTX, args: [], stdout });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${SKILL_REL_PATH}`);
    expect(lines).toContain(`created ${CLAUDE_MD_REL_PATH}`);
  });

  test("--json emits the agents.result envelope", () => {
    const stdout = capture();
    runAgents({ root, output: JSON_CTX, args: [], stdout });
    const envelope = JSON.parse(stdout.text()) as { schemaVersion: number; kind: string };
    expect(envelope.schemaVersion).toBe(1);
    expect(envelope.kind).toBe("agents.result");
  });
});

describe("lore agents — argument validation", () => {
  test("a positional argument is a usage error (exit 2)", () => {
    const err = usageError(["nope"]);
    expect(err.type).toBe("usage");
    expect(err.message).toContain("takes no arguments");
  });

  test("an unknown flag is a usage error (exit 2)", () => {
    expect(usageError(["--bogus"]).type).toBe("usage");
  });

  /** Run `agents` with `args` and return the {@link LoreError} it throws. */
  function usageError(args: string[]): LoreError {
    try {
      runAgents({ root, output: JSON_CTX, args, stdout: capture() });
    } catch (err) {
      if (err instanceof LoreError) {
        return err;
      }
      throw err;
    }
    throw new Error("expected a LoreError, but runAgents returned");
  }
});

describe("command-surface lockstep — the bridge names only real commands", () => {
  /** Drive the real router for `argv` in an empty cwd, returning captured stderr. */
  async function runCli(argv: string[]): Promise<string> {
    const stderr = capture();
    const cwd = mkdtempSync(join(tmpdir(), "lore-agents-probe-"));
    try {
      await run(["bun", "lore", ...argv], { cwd, stdout: capture(), stderr, isTTY: false, env: {} });
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
    return stderr.text();
  }

  test("the probe is valid: an unknown command DOES report `unknown command`", async () => {
    expect(await runCli(["definitely-not-a-command"])).toContain("unknown command");
  });

  test("every command the bridge advertises is dispatched by the real router (not a phantom)", async () => {
    for (const cmd of LORE_COMMANDS) {
      // A bogus flag reaches (or is rejected by) the command itself — never the router's
      // `unknown command` path, which only fires for an unrecognized subcommand name.
      const stderr = await runCli([cmd.name, "--zzz-not-a-real-flag"]);
      expect(stderr).not.toContain("unknown command");
    }
  });
});
