/**
 * consumer-scaffold.test.ts — `lore scaffold mkdocs` (LORE-39) and `lore scaffold docusaurus`
 * (LORE-40): the additive MkDocs and Docusaurus consumer configs.
 *
 * AC#1 ("build succeeds on the bundle") is exercised end-to-end by the `scaffold-mkdocs` and
 * `scaffold-docusaurus` CI jobs (a real `mkdocs build` / `docusaurus build` against the
 * scaffolded config + this repo's own bundle) — real Python/MkDocs and Node/Docusaurus
 * toolchains are deliberately not `bun test` dependencies (matching the "compile smoke" job's
 * separation for `bun build --compile`). This suite pins the generated bytes and exercises the
 * command's own contract: never-silent-clobber (exit 5 without `--force`), the all-or-nothing
 * pre-flight, and argument validation. Docusaurus's rollback/pre-flight edge cases (read-only
 * dir, unreadable pre-existing file, a freshly-ensured directory rolled back on a later
 * failure, etc.) are not re-tested per target — both targets share the exact same
 * `writeAllOrRollback` primitive, already exercised exhaustively by the mkdocs suite below.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { load as yamlLoad } from "js-yaml";
import { runScaffold, type ScaffoldResult } from "../src/commands/scaffold";
import { parseConcept } from "../src/core/concept";
import {
  buildDocusaurusScaffold,
  buildMkdocsScaffold,
  DOCUSAURUS_CONFIG_REL_PATH,
  MKDOCS_CONFIG_REL_PATH,
  SIDEBARS_REL_PATH,
  TAGS_INDEX_REL_PATH,
  WEBSITE_PACKAGE_JSON_REL_PATH,
} from "../src/core/consumer-scaffold";
import { LoreError } from "../src/errors";
import type { OutputContext } from "../src/output";
import { capture, expectError } from "./helpers";

const JSON_CTX: OutputContext = { mode: "json", color: false };
const PLAIN_CTX: OutputContext = { mode: "plain", color: false };
const FIXED_CLOCK = (): Date => new Date("2026-07-11T12:00:00Z");

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "lore-scaffold-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Run `scaffold` in JSON mode and return the parsed `data` payload plus the exit code. */
function scaffold(args: string[]): { code: number; result: ScaffoldResult } {
  const stdout = capture();
  const code = runScaffold({ root, output: JSON_CTX, args, stdout, clock: FIXED_CLOCK });
  const envelope = JSON.parse(stdout.text()) as { kind: string; data: ScaffoldResult };
  expect(envelope.kind).toBe("scaffold.result");
  return { code, result: envelope.data };
}

describe("core/consumer-scaffold — buildMkdocsScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildMkdocsScaffold(opts)).toEqual(buildMkdocsScaffold(opts));
  });

  test("plans exactly mkdocs.yml (repo root) and docs/tags.md, in that order", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(plan.files.map((f) => f.path)).toEqual([MKDOCS_CONFIG_REL_PATH, TAGS_INDEX_REL_PATH]);
  });

  test("mkdocs.yml carries every documented setting (consumer-compatibility.md §3.3 / ADR-0010 §2)", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "my-project" });
    const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
    expect(yaml).toContain('site_name: "my-project"');
    expect(yaml).toContain("docs_dir: docs");
    expect(yaml).toContain("name: material");
    expect(yaml).toContain("navigation.indexes");
    expect(yaml).toContain("- search");
    expect(yaml).toContain("- tags");
    expect(yaml).toContain("strict: false");
    expect(yaml).toContain("absolute_links: relative_to_docs");
    expect(yaml).toContain("not_found: warn");
    expect(yaml).toContain("anchors: warn");
    expect(yaml).toContain("omitted_files: ignore");
    expect(yaml).toContain("not_in_nav: |\n  /log.md");
  });

  test("site_name is always double-quoted, so a YAML-1.1 boolean/null/numeric-looking directory name is never type-coerced", () => {
    // Regression: an earlier "quote only if unsafe" heuristic's blocklist covered only
    // true/false/null/~, missing the wider YAML 1.1 core-schema literals (yes/no/on/off/y/n,
    // case-insensitive) a PyYAML-based loader (mkdocs') resolves as booleans — a repo directory
    // named e.g. "off" would silently become a bool, failing mkdocs' `site_name: str` requirement
    // despite `lore scaffold mkdocs` reporting success. Always double-quoting removes the whole
    // class of YAML-implicit-typing surprises rather than trying to enumerate them.
    for (const siteName of ["off", "Off", "no", "yes", "on", "y", "n", "2026", "null", "~", "true-ish"]) {
      const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName });
      const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
      const parsed = yamlLoad(yaml) as { site_name: unknown };
      expect(parsed.site_name).toBe(siteName);
      expect(typeof parsed.site_name).toBe("string");
    }
  });

  test("docs/tags.md is a valid OKF Reference concept carrying the Material tags marker", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
    expect(concept.frontmatter.title).toBe("Tags");
    expect(raw).toContain("<!-- material/tags -->");
  });

  test("stamps docs/tags.md's timestamp from the given option", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-01-02T03:04:05.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    expect(raw).toContain("timestamp: 2026-01-02T03:04:05.000Z");
  });
});

describe("lore scaffold mkdocs — fresh scaffold", () => {
  test("creates both files and exits 0", () => {
    const { code, result } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    expect(result.target).toBe("mkdocs");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "created" },
      { path: TAGS_INDEX_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(true);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });

  test("creates the docs/ directory when the bundle was never initialized", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    scaffold(["mkdocs"]);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });
});

describe("lore scaffold mkdocs — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["mkdocs"]);
    const yamlBefore = readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    const tagsBefore = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.message).toContain(MKDOCS_CONFIG_REL_PATH);
    expect(err.message).toContain(TAGS_INDEX_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe(yamlBefore);
    expect(readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8")).toBe(tagsBefore);
  });

  test("a hand-authored mkdocs.yml alone (tags.md absent) still refuses without --force", () => {
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: hand-authored\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.input).toMatchObject({ paths: [MKDOCS_CONFIG_REL_PATH] });
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: hand-authored\n");
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(false);
  });

  test("--force overwrites both existing files and reports `updated`", () => {
    scaffold(["mkdocs"]);
    const { code, result } = scaffold(["mkdocs", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "updated" },
      { path: TAGS_INDEX_REL_PATH, action: "updated" },
    ]);
  });

  test("--force on a fresh repo still reports `created` (not `updated`)", () => {
    const { result } = scaffold(["mkdocs", "--force"]);
    expect(result.files.every((f) => f.action === "created")).toBe(true);
  });

  // POSIX-only: a read-only directory doesn't reliably block a write on Windows the same way.
  test.skipIf(process.platform === "win32")(
    "a write failure partway through the plan rolls back the earlier file (true all-or-nothing)",
    () => {
      // Regression: the write loop used to leave mkdocs.yml (planned first) behind on disk when
      // the docs/tags.md write failed, contradicting the documented all-or-nothing guarantee.
      mkdirSync(join(root, "docs"), { recursive: true, mode: 0o555 });
      try {
        const err = expectError("denied", () =>
          runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
        );
        expect(err.type).toBe("denied");
        expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(false);
      } finally {
        chmodSync(join(root, "docs"), 0o755);
        rmSync(join(root, "docs"), { recursive: true, force: true });
      }
    },
  );

  test("--force run's rollback restores the PREVIOUS bytes of an already-overwritten file, not just a delete", () => {
    scaffold(["mkdocs"]);
    const yamlBefore = readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    // Make the SECOND planned write (docs/tags.md) fail after the FIRST (mkdocs.yml) succeeds,
    // by replacing tags.md with a directory (a write there throws EISDIR).
    rmSync(join(root, TAGS_INDEX_REL_PATH));
    mkdirSync(join(root, TAGS_INDEX_REL_PATH));
    expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe(yamlBefore);
  });

  test("a pre-existing file that is writable but unreadable is never deleted by a rollback (review #1)", () => {
    if (process.getuid?.() === 0) {
      return; // root bypasses read-permission checks, so this repro can't be set up
    }
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: original\n");
    chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o200); // write-only: unreadable, even by the owner
    let unreadable = false;
    try {
      readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    } catch {
      unreadable = true;
    }
    if (!unreadable) {
      chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o644);
      return; // environment ignores the mode (e.g. a permissive filesystem) — skip
    }
    // A later planned write is ALSO forced to fail, mirroring the original bug's repro shape
    // (the pre-fix rollback only manifested once some later step threw); the fix must refuse
    // outright before ever reaching this, but the forced failure is left in place regardless so
    // the assertion below holds under either fix strategy.
    mkdirSync(join(root, TAGS_INDEX_REL_PATH), { recursive: true });
    let thrown: unknown;
    try {
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() });
    } catch (err) {
      thrown = err;
    } finally {
      chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o644); // restore so afterEach's rmSync can clean up
    }
    expect(thrown).toBeInstanceOf(LoreError);
    expect((thrown as LoreError).type).toBe("denied");
    // Regression: the old rollback used `before === undefined` to mean "delete on rollback" — true
    // both when a file never existed AND when it existed but couldn't be read — so this
    // pre-existing, merely-unreadable file used to get DELETED by the rollback triggered by the
    // later (docs/tags.md) failure. A file that existed before the command ran must never be
    // touched, let alone deleted.
    expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(true);
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: original\n");
  });

  test("a run against a repo with no docs/ rolls back the freshly-created directory on a later failure (review #2)", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    // Force the FIRST planned write (mkdocs.yml, at the repo root) to fail structurally — a
    // directory sitting where the file must go — so the failure happens strictly AFTER `docs/`
    // has already been freshly created by this same run's directory-ensure step.
    mkdirSync(join(root, MKDOCS_CONFIG_REL_PATH), { recursive: true });
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(err.type).toBe("conflict");
    // Regression: `ensureDir(docs/, …)` used to run outside the write-loop's rollback entirely, so
    // a freshly created (and, since nothing was ever written into it, still-empty) `docs/` was left
    // behind on disk after this failure — breaking the "writes nothing on failure" contract for the
    // directory itself.
    expect(existsSync(join(root, "docs"))).toBe(false);
  });
});

describe("core/consumer-scaffold — buildDocusaurusScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildDocusaurusScaffold(opts)).toEqual(buildDocusaurusScaffold(opts));
  });

  test("plans exactly website/package.json, website/docusaurus.config.js, website/sidebars.js, in that order", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(plan.dirs).toEqual(["website"]);
    expect(plan.files.map((f) => f.path)).toEqual([
      WEBSITE_PACKAGE_JSON_REL_PATH,
      DOCUSAURUS_CONFIG_REL_PATH,
      SIDEBARS_REL_PATH,
    ]);
  });

  test("docusaurus.config.js carries every documented setting, as CommonJS (consumer-compatibility.md §3.4 / ADR-0010 §2)", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "my-project" });
    const js = plan.files.find((f) => f.path === DOCUSAURUS_CONFIG_REL_PATH)?.contents ?? "";
    expect(js).toContain("module.exports = {");
    expect(js).not.toMatch(/^export default/m);
    expect(js).toContain('title: "my-project"');
    expect(js).toContain('format: "detect"');
    expect(js).toContain('onBrokenMarkdownLinks: "warn"');
    expect(js).toContain('onBrokenLinks: "warn"');
    expect(js).toContain('onBrokenAnchors: "warn"');
    expect(js).toContain("trailingSlash: false");
    expect(js).toContain('path: "../docs"');
    expect(js).toContain('routeBasePath: "/"');
    expect(js).toContain('sidebarPath: "./sidebars.js"');
    expect(js).toContain("blog: false");
  });

  test("website/package.json is valid JSON, pins Docusaurus packages in lockstep, and never sets type:module", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === WEBSITE_PACKAGE_JSON_REL_PATH)?.contents ?? "";
    const pkg = JSON.parse(raw) as {
      type?: string;
      scripts: { build: string };
      dependencies: Record<string, string>;
    };
    expect(pkg.type).toBeUndefined();
    expect(pkg.scripts.build).toBe("docusaurus build");
    expect(pkg.dependencies["@docusaurus/core"]).toBe(pkg.dependencies["@docusaurus/preset-classic"]);
    expect(pkg.dependencies.react).toBeDefined();
    expect(pkg.dependencies["react-dom"]).toBeDefined();
  });

  test("sidebars.js is a fully-autogenerated CommonJS sidebar", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const js = plan.files.find((f) => f.path === SIDEBARS_REL_PATH)?.contents ?? "";
    expect(js).toContain("module.exports = {");
    expect(js).not.toMatch(/^export default/m);
    expect(js).toContain('type: "autogenerated"');
    expect(js).toContain('dirName: "."');
  });
});

describe("lore scaffold docusaurus — fresh scaffold", () => {
  test("creates all three files and exits 0", () => {
    const { code, result } = scaffold(["docusaurus"]);
    expect(code).toBe(0);
    expect(result.target).toBe("docusaurus");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: WEBSITE_PACKAGE_JSON_REL_PATH, action: "created" },
      { path: DOCUSAURUS_CONFIG_REL_PATH, action: "created" },
      { path: SIDEBARS_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, WEBSITE_PACKAGE_JSON_REL_PATH))).toBe(true);
    expect(existsSync(join(root, DOCUSAURUS_CONFIG_REL_PATH))).toBe(true);
    expect(existsSync(join(root, SIDEBARS_REL_PATH))).toBe(true);
  });

  test("creates the website/ directory when it does not already exist", () => {
    expect(existsSync(join(root, "website"))).toBe(false);
    scaffold(["docusaurus"]);
    expect(existsSync(join(root, "website"))).toBe(true);
  });
});

describe("lore scaffold docusaurus — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["docusaurus"]);
    const configBefore = readFileSync(join(root, DOCUSAURUS_CONFIG_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["docusaurus"], stdout: capture() }),
    );
    expect(err.message).toContain(WEBSITE_PACKAGE_JSON_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, DOCUSAURUS_CONFIG_REL_PATH), "utf8")).toBe(configBefore);
  });

  test("--force overwrites all three existing files and reports `updated`", () => {
    scaffold(["docusaurus"]);
    const { code, result } = scaffold(["docusaurus", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files.every((f) => f.action === "updated")).toBe(true);
  });

  test("a pre-existing non-directory file occupying website/ is reported as a friendly conflict, not a deep crash (review #1)", () => {
    // Regression: the preflight used to check only plan.files, never plan.dirs, so a plain file
    // sitting where website/ needs to be a directory skipped the plan-wide "already exists"
    // conflict message entirely and only surfaced later as a generic ensureDir error.
    writeFileSync(join(root, "website"), "not a directory\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["docusaurus"], stdout: capture() }),
    );
    expect(err.message).toContain("website");
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, "website"), "utf8")).toBe("not a directory\n");
  });
});

describe("lore scaffold docusaurus — profile independence", () => {
  test("a malformed .lore/profile.toml does NOT block it (buildDocusaurusScaffold never reads profile)", () => {
    // Regression: runScaffold used to call loadProfile() unconditionally for every target, so a
    // repo with a broken profile file (unrelated to Docusaurus) blocked `lore scaffold docusaurus`
    // even though ConsumerScaffoldOptions.profile is documented as unused by this builder.
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(join(root, ".lore/profile.toml"), "not = [valid");
    const { code, result } = scaffold(["docusaurus"]);
    expect(code).toBe(0);
    expect(result.target).toBe("docusaurus");
  });
});

describe("lore scaffold docusaurus — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file plus a summary", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["docusaurus"], stdout, clock: FIXED_CLOCK });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${WEBSITE_PACKAGE_JSON_REL_PATH}`);
    expect(lines).toContain(`created ${DOCUSAURUS_CONFIG_REL_PATH}`);
    expect(lines).toContain(`created ${SIDEBARS_REL_PATH}`);
    expect(lines).toContain("scaffolded docusaurus config (3 files)");
  });
});

describe("lore scaffold — argument validation", () => {
  function usageError(args: string[]): LoreError {
    return expectError("usage", () => runScaffold({ root, output: JSON_CTX, args, stdout: capture() }));
  }

  test("no target is a usage error", () => {
    expect(usageError([]).message).toContain("needs a target");
  });

  test("an unknown target is a usage error", () => {
    expect(usageError(["hugo"]).message).toContain('unknown scaffold target "hugo"');
  });

  test("a documented-but-unimplemented target (obsidian) is a usage error, not a crash", () => {
    expect(usageError(["obsidian"]).message).toContain("not implemented yet");
  });

  test("an extra positional is a usage error", () => {
    expect(usageError(["mkdocs", "extra"]).message).toContain('unexpected argument "extra"');
  });

  test("an unknown flag is a usage error", () => {
    expect(usageError(["mkdocs", "--bogus"]).type).toBe("usage");
  });
});

describe("lore scaffold mkdocs — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file plus a summary", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${MKDOCS_CONFIG_REL_PATH}`);
    expect(lines).toContain(`created ${TAGS_INDEX_REL_PATH}`);
    expect(lines).toContain("scaffolded mkdocs config (2 files)");
  });

  test("--json emits the scaffold.result envelope", () => {
    const stdout = capture();
    runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const envelope = JSON.parse(stdout.text()) as { schemaVersion: number; kind: string };
    expect(envelope.schemaVersion).toBe(1);
    expect(envelope.kind).toBe("scaffold.result");
  });
});

describe("lore scaffold mkdocs — a pre-existing custom profile without Reference", () => {
  test("still scaffolds docs/tags.md, without a $schema modeline", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(
      join(root, ".lore/profile.toml"),
      [
        "[profile]",
        'name = "demo"',
        'okf_version = "0.1"',
        "[base.fields]",
        "type = { required = true }",
        "[[types]]",
        'name = "Doc"',
      ].join("\n"),
    );
    const { code } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    const raw = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");
    expect(raw).not.toContain("yaml-language-server");
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
  });

  test("a malformed .lore/profile.toml surfaces as a validation error (exit 6), not a crash", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(join(root, ".lore/profile.toml"), "not = [valid");
    const err = expectError("validation", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.type).toBe("validation");
  });
});
