/**
 * consumer-scaffold.test.ts — `lore scaffold mkdocs` (LORE-39) and `lore scaffold docusaurus`
 * (LORE-40): the additive MkDocs and Docusaurus consumer configs.
 *
 * AC#1 ("build succeeds on the bundle") is exercised end-to-end by the `scaffold-mkdocs` and
 * `scaffold-docusaurus` CI jobs (a real `mkdocs build` / `docusaurus build` against the
 * scaffolded config + this repo's own bundle) — real Python/MkDocs and Node/Docusaurus
 * toolchains are deliberately not `bun test` dependencies (matching the "compile smoke" job's
 * separation for `bun build --compile`). This suite pins the generated bytes and exercises the
 * command's own contract: never-silent-clobber (exit 5 without `--force`), the all-or-nothing
 * pre-flight, and argument validation. Docusaurus's rollback/pre-flight edge cases (read-only
 * dir, unreadable pre-existing file, a freshly-ensured directory rolled back on a later
 * failure, etc.) are not re-tested per target — both targets share the exact same
 * `writeAllOrRollback` primitive, already exercised exhaustively by the mkdocs suite below.
 * Obsidian (LORE-41) gets its own narrow rollback/pre-flight regression tests (LORE-55) despite
 * sharing that same primitive — its bug was in {@link buildObsidianScaffold}'s own `dirs` list,
 * a per-target plan defect the shared-primitive tests below can't catch.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { load as yamlLoad } from "js-yaml";
import { runScaffold, type ScaffoldResult } from "../src/commands/scaffold";
import { parseConcept } from "../src/core/concept";
import {
  buildDocusaurusScaffold,
  buildMkdocsScaffold,
  buildObsidianScaffold,
  DOCUSAURUS_CONFIG_REL_PATH,
  MKDOCS_CONFIG_REL_PATH,
  OBSIDIAN_APP_JSON_REL_PATH,
  OBSIDIAN_GITIGNORE_REL_PATH,
  OBSIDIAN_GUIDANCE_NOTES,
  SIDEBARS_REL_PATH,
  TAGS_INDEX_REL_PATH,
  WEBSITE_PACKAGE_JSON_REL_PATH,
} from "../src/core/consumer-scaffold";
import { LoreError } from "../src/errors";
import type { OutputContext } from "../src/output";
import { capture, expectError } from "./helpers";

const JSON_CTX: OutputContext = { mode: "json", color: false };
const PLAIN_CTX: OutputContext = { mode: "plain", color: false };
const FIXED_CLOCK = (): Date => new Date("2026-07-11T12:00:00Z");

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "lore-scaffold-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Run `scaffold` in JSON mode and return the parsed `data` payload plus the exit code. */
function scaffold(args: string[]): { code: number; result: ScaffoldResult } {
  const stdout = capture();
  const code = runScaffold({ root, output: JSON_CTX, args, stdout, clock: FIXED_CLOCK });
  const envelope = JSON.parse(stdout.text()) as { kind: string; data: ScaffoldResult };
  expect(envelope.kind).toBe("scaffold.result");
  return { code, result: envelope.data };
}

describe("core/consumer-scaffold — buildMkdocsScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildMkdocsScaffold(opts)).toEqual(buildMkdocsScaffold(opts));
  });

  test("plans exactly mkdocs.yml (repo root) and docs/tags.md, in that order", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(plan.files.map((f) => f.path)).toEqual([MKDOCS_CONFIG_REL_PATH, TAGS_INDEX_REL_PATH]);
  });

  test("mkdocs.yml carries every documented setting (consumer-compatibility.md §3.3 / ADR-0010 §2)", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "my-project" });
    const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
    expect(yaml).toContain('site_name: "my-project"');
    expect(yaml).toContain("docs_dir: docs");
    expect(yaml).toContain("name: material");
    expect(yaml).toContain("navigation.indexes");
    expect(yaml).toContain("- search");
    expect(yaml).toContain("- tags");
    expect(yaml).toContain("strict: false");
    expect(yaml).toContain("absolute_links: relative_to_docs");
    expect(yaml).toContain("not_found: warn");
    expect(yaml).toContain("anchors: warn");
    expect(yaml).toContain("omitted_files: ignore");
    expect(yaml).toContain("not_in_nav: |\n  /log.md");
  });

  test("site_name is always double-quoted, so a YAML-1.1 boolean/null/numeric-looking directory name is never type-coerced", () => {
    // Regression: an earlier "quote only if unsafe" heuristic's blocklist covered only
    // true/false/null/~, missing the wider YAML 1.1 core-schema literals (yes/no/on/off/y/n,
    // case-insensitive) a PyYAML-based loader (mkdocs') resolves as booleans — a repo directory
    // named e.g. "off" would silently become a bool, failing mkdocs' `site_name: str` requirement
    // despite `lore scaffold mkdocs` reporting success. Always double-quoting removes the whole
    // class of YAML-implicit-typing surprises rather than trying to enumerate them.
    for (const siteName of ["off", "Off", "no", "yes", "on", "y", "n", "2026", "null", "~", "true-ish"]) {
      const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName });
      const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
      const parsed = yamlLoad(yaml) as { site_name: unknown };
      expect(parsed.site_name).toBe(siteName);
      expect(typeof parsed.site_name).toBe("string");
    }
  });

  test("docs/tags.md is a valid OKF Reference concept carrying the Material tags marker", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
    expect(concept.frontmatter.title).toBe("Tags");
    expect(raw).toContain("<!-- material/tags -->");
  });

  test("stamps docs/tags.md's timestamp from the given option", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-01-02T03:04:05.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    expect(raw).toContain("timestamp: 2026-01-02T03:04:05.000Z");
  });
});

describe("lore scaffold mkdocs — fresh scaffold", () => {
  test("creates both files and exits 0", () => {
    const { code, result } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    expect(result.target).toBe("mkdocs");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "created" },
      { path: TAGS_INDEX_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(true);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });

  test("creates the docs/ directory when the bundle was never initialized", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    scaffold(["mkdocs"]);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });
});

describe("lore scaffold mkdocs — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["mkdocs"]);
    const yamlBefore = readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    const tagsBefore = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.message).toContain(MKDOCS_CONFIG_REL_PATH);
    expect(err.message).toContain(TAGS_INDEX_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe(yamlBefore);
    expect(readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8")).toBe(tagsBefore);
  });

  test("a hand-authored mkdocs.yml alone (tags.md absent) still refuses without --force", () => {
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: hand-authored\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.input).toMatchObject({ paths: [MKDOCS_CONFIG_REL_PATH] });
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: hand-authored\n");
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(false);
  });

  test("--force overwrites both existing files and reports `updated`", () => {
    scaffold(["mkdocs"]);
    const { code, result } = scaffold(["mkdocs", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "updated" },
      { path: TAGS_INDEX_REL_PATH, action: "updated" },
    ]);
  });

  test("a structural directory blocker AND a pre-existing file together yield a hint conveying both remedies (LORE-238)", () => {
    // MKDOCS_CONFIG_REL_PATH ("mkdocs.yml") is a top-level file, independent of docs/, so it can
    // pre-exist as a genuine file collision at the same time docs/ is blocked by a plain file —
    // exercising AC#3's "both" case in one run.
    writeFileSync(join(root, "docs"), "not a directory\n");
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: hand-authored\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.message).toContain("docs");
    expect(err.message).toContain(MKDOCS_CONFIG_REL_PATH);
    // Both remedies must be conveyed: --force for the file, remove/rename for the dir-blocker.
    expect(err.hint).toContain("--force");
    expect(err.hint).toContain("remove or rename");
    expect(readFileSync(join(root, "docs"), "utf8")).toBe("not a directory\n");
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: hand-authored\n");
  });

  test("--force on a fresh repo still reports `created` (not `updated`)", () => {
    const { result } = scaffold(["mkdocs", "--force"]);
    expect(result.files.every((f) => f.action === "created")).toBe(true);
  });

  // POSIX-only: a read-only directory doesn't reliably block a write on Windows the same way.
  test.skipIf(process.platform === "win32")(
    "a write failure partway through the plan rolls back the earlier file (true all-or-nothing)",
    () => {
      // Regression: the write loop used to leave mkdocs.yml (planned first) behind on disk when
      // the docs/tags.md write failed, contradicting the documented all-or-nothing guarantee.
      mkdirSync(join(root, "docs"), { recursive: true, mode: 0o555 });
      try {
        const err = expectError("denied", () =>
          runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
        );
        expect(err.type).toBe("denied");
        expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(false);
      } finally {
        chmodSync(join(root, "docs"), 0o755);
        rmSync(join(root, "docs"), { recursive: true, force: true });
      }
    },
  );

  test("--force run's rollback restores the PREVIOUS bytes of an already-overwritten file, not just a delete", () => {
    scaffold(["mkdocs"]);
    const yamlBefore = readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    // Make the SECOND planned write (docs/tags.md) fail after the FIRST (mkdocs.yml) succeeds,
    // by replacing tags.md with a directory (a write there throws EISDIR).
    rmSync(join(root, TAGS_INDEX_REL_PATH));
    mkdirSync(join(root, TAGS_INDEX_REL_PATH));
    expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe(yamlBefore);
  });

  test("a pre-existing file that is writable but unreadable is never deleted by a rollback (review #1)", () => {
    if (process.getuid?.() === 0) {
      return; // root bypasses read-permission checks, so this repro can't be set up
    }
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: original\n");
    chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o200); // write-only: unreadable, even by the owner
    let unreadable = false;
    try {
      readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    } catch {
      unreadable = true;
    }
    if (!unreadable) {
      chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o644);
      return; // environment ignores the mode (e.g. a permissive filesystem) — skip
    }
    // A later planned write is ALSO forced to fail, mirroring the original bug's repro shape
    // (the pre-fix rollback only manifested once some later step threw); the fix must refuse
    // outright before ever reaching this, but the forced failure is left in place regardless so
    // the assertion below holds under either fix strategy.
    mkdirSync(join(root, TAGS_INDEX_REL_PATH), { recursive: true });
    let thrown: unknown;
    try {
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() });
    } catch (err) {
      thrown = err;
    } finally {
      chmodSync(join(root, MKDOCS_CONFIG_REL_PATH), 0o644); // restore so afterEach's rmSync can clean up
    }
    expect(thrown).toBeInstanceOf(LoreError);
    expect((thrown as LoreError).type).toBe("denied");
    // Regression: the old rollback used `before === undefined` to mean "delete on rollback" — true
    // both when a file never existed AND when it existed but couldn't be read — so this
    // pre-existing, merely-unreadable file used to get DELETED by the rollback triggered by the
    // later (docs/tags.md) failure. A file that existed before the command ran must never be
    // touched, let alone deleted.
    expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(true);
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: original\n");
  });

  test("a run against a repo with no docs/ rolls back the freshly-created directory on a later failure (review #2)", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    // Force the FIRST planned write (mkdocs.yml, at the repo root) to fail structurally — a
    // directory sitting where the file must go — so the failure happens strictly AFTER `docs/`
    // has already been freshly created by this same run's directory-ensure step.
    mkdirSync(join(root, MKDOCS_CONFIG_REL_PATH), { recursive: true });
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(err.type).toBe("conflict");
    // Regression: `ensureDir(docs/, …)` used to run outside the write-loop's rollback entirely, so
    // a freshly created (and, since nothing was ever written into it, still-empty) `docs/` was left
    // behind on disk after this failure — breaking the "writes nothing on failure" contract for the
    // directory itself.
    expect(existsSync(join(root, "docs"))).toBe(false);
  });
});

describe("lore scaffold mkdocs — refuses to write through a symlink (LORE-76)", () => {
  let outside: string;

  beforeEach(() => {
    outside = mkdtempSync(join(tmpdir(), "lore-scaffold-outside-"));
  });
  afterEach(() => {
    rmSync(outside, { recursive: true, force: true });
  });

  test("a symlinked docs/ ancestor directory is refused, not followed — nothing is written outside the repo", () => {
    // docs/ doesn't need to pre-exist for buildMkdocsScaffold's plan, but the plan's OWN dirs list
    // includes it (see the fresh-scaffold test above) — a symlink standing in for it is exactly the
    // "symlinked ancestor" case AC1 names, since docs/tags.md's write walks through it.
    symlinkSync(outside, join(root, "docs"));
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.message).toContain("docs");
    expect(err.message.toLowerCase()).toContain("symlink");
    // Confirms the guard, not a coincidental EEXIST, is what stopped this: without LORE-76's fix,
    // `mkdirSync(docs, {recursive:true})` + a `docs/tags.md` write would transparently follow the
    // symlink and land the generated file inside `outside` (the task's own live repro).
    expect(existsSync(join(outside, "tags.md"))).toBe(false);
    expect(existsSync(join(root, "mkdocs.yml"))).toBe(false); // all-or-nothing: nothing else written either
  });

  test("a symlinked mkdocs.yml final target is refused under --force — the outside file's content is untouched", () => {
    const outsideFile = join(outside, "mkdocs.yml");
    writeFileSync(outsideFile, "SENSITIVE PRE-EXISTING CONTENT — must never be overwritten\n");
    symlinkSync(outsideFile, join(root, MKDOCS_CONFIG_REL_PATH));
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(err.message).toContain(MKDOCS_CONFIG_REL_PATH);
    expect(err.message.toLowerCase()).toContain("symlink");
    // The task's own live repro: without LORE-76's fix, `--force`'s overwrite branch follows the
    // symlink (existsSync/readFileSync/writeFileSync all resolve through it) and clobbers whatever
    // real file the symlink points at, anywhere on disk.
    expect(readFileSync(outsideFile, "utf8")).toBe("SENSITIVE PRE-EXISTING CONTENT — must never be overwritten\n");
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(false); // all-or-nothing: nothing else written
  });

  test("a symlinked ancestor is refused even under --force (the guard runs regardless of the write discipline)", () => {
    symlinkSync(outside, join(root, "docs"));
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs", "--force"], stdout: capture() }),
    );
    expect(err.message.toLowerCase()).toContain("symlink");
    expect(existsSync(join(outside, "tags.md"))).toBe(false);
  });
});

describe("core/consumer-scaffold — buildDocusaurusScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildDocusaurusScaffold(opts)).toEqual(buildDocusaurusScaffold(opts));
  });

  test("plans exactly website/package.json, website/docusaurus.config.js, website/sidebars.js, in that order", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(plan.dirs).toEqual(["website"]);
    expect(plan.files.map((f) => f.path)).toEqual([
      WEBSITE_PACKAGE_JSON_REL_PATH,
      DOCUSAURUS_CONFIG_REL_PATH,
      SIDEBARS_REL_PATH,
    ]);
  });

  test("docusaurus.config.js carries every documented setting, as CommonJS (consumer-compatibility.md §3.4 / ADR-0010 §2)", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "my-project" });
    const js = plan.files.find((f) => f.path === DOCUSAURUS_CONFIG_REL_PATH)?.contents ?? "";
    expect(js).toContain("module.exports = {");
    expect(js).not.toMatch(/^export default/m);
    expect(js).toContain('title: "my-project"');
    expect(js).toContain('format: "detect"');
    expect(js).toContain('onBrokenMarkdownLinks: "warn"');
    expect(js).toContain('onBrokenLinks: "warn"');
    expect(js).toContain('onBrokenAnchors: "warn"');
    expect(js).toContain("trailingSlash: false");
    expect(js).toContain('path: "../docs"');
    expect(js).toContain('routeBasePath: "/"');
    expect(js).toContain('sidebarPath: "./sidebars.js"');
    expect(js).toContain("blog: false");
  });

  test("website/package.json is valid JSON, pins Docusaurus packages in lockstep, and never sets type:module", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === WEBSITE_PACKAGE_JSON_REL_PATH)?.contents ?? "";
    const pkg = JSON.parse(raw) as {
      type?: string;
      scripts: { build: string };
      dependencies: Record<string, string>;
    };
    expect(pkg.type).toBeUndefined();
    expect(pkg.scripts.build).toBe("docusaurus build");
    expect(pkg.dependencies["@docusaurus/core"]).toBe(pkg.dependencies["@docusaurus/preset-classic"]);
    expect(pkg.dependencies.react).toBeDefined();
    expect(pkg.dependencies["react-dom"]).toBeDefined();
  });

  test("sidebars.js is a fully-autogenerated CommonJS sidebar", () => {
    const plan = buildDocusaurusScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const js = plan.files.find((f) => f.path === SIDEBARS_REL_PATH)?.contents ?? "";
    expect(js).toContain("module.exports = {");
    expect(js).not.toMatch(/^export default/m);
    expect(js).toContain('type: "autogenerated"');
    expect(js).toContain('dirName: "."');
  });
});

describe("lore scaffold docusaurus — fresh scaffold", () => {
  test("creates all three files and exits 0", () => {
    const { code, result } = scaffold(["docusaurus"]);
    expect(code).toBe(0);
    expect(result.target).toBe("docusaurus");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: WEBSITE_PACKAGE_JSON_REL_PATH, action: "created" },
      { path: DOCUSAURUS_CONFIG_REL_PATH, action: "created" },
      { path: SIDEBARS_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, WEBSITE_PACKAGE_JSON_REL_PATH))).toBe(true);
    expect(existsSync(join(root, DOCUSAURUS_CONFIG_REL_PATH))).toBe(true);
    expect(existsSync(join(root, SIDEBARS_REL_PATH))).toBe(true);
  });

  test("creates the website/ directory when it does not already exist", () => {
    expect(existsSync(join(root, "website"))).toBe(false);
    scaffold(["docusaurus"]);
    expect(existsSync(join(root, "website"))).toBe(true);
  });
});

describe("lore scaffold docusaurus — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["docusaurus"]);
    const configBefore = readFileSync(join(root, DOCUSAURUS_CONFIG_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["docusaurus"], stdout: capture() }),
    );
    expect(err.message).toContain(WEBSITE_PACKAGE_JSON_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, DOCUSAURUS_CONFIG_REL_PATH), "utf8")).toBe(configBefore);
  });

  test("--force overwrites all three existing files and reports `updated`", () => {
    scaffold(["docusaurus"]);
    const { code, result } = scaffold(["docusaurus", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files.every((f) => f.action === "updated")).toBe(true);
  });

  test("a pre-existing non-directory file occupying website/ is reported as a friendly conflict, not a deep crash (review #1)", () => {
    // Regression: the preflight used to check only plan.files, never plan.dirs, so a plain file
    // sitting where website/ needs to be a directory skipped the plan-wide "already exists"
    // conflict message entirely and only surfaced later as a generic ensureDir error.
    writeFileSync(join(root, "website"), "not a directory\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["docusaurus"], stdout: capture() }),
    );
    expect(err.message).toContain("website");
    // A structural directory blocker is NOT fixed by --force (LORE-238): the hint must not claim
    // it, and must instead direct the user to remove/rename the non-directory entry.
    expect(err.hint).not.toContain("--force");
    expect(err.hint).toContain("remove or rename");
    expect(readFileSync(join(root, "website"), "utf8")).toBe("not a directory\n");
  });

  test("--force does NOT fix a structural directory blocker and still fails with a conflict (LORE-238)", () => {
    // Regression: --force skips this command's own preflight entirely, so a plain file occupying
    // website/ is only caught later by writeAllOrRollback -> ensureDir's mkdirSync, which throws
    // EEXIST on the same entry — remapped to a second `conflict`, never a successful overwrite.
    // This is the reason the preflight hint above must never tell the user --force will help.
    writeFileSync(join(root, "website"), "not a directory\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["docusaurus", "--force"], stdout: capture() }),
    );
    expect(err.type).toBe("conflict");
    expect(readFileSync(join(root, "website"), "utf8")).toBe("not a directory\n");
  });
});

describe("lore scaffold docusaurus — profile independence", () => {
  test("a malformed .lore/profile.toml does NOT block it (buildDocusaurusScaffold never reads profile)", () => {
    // Regression: runScaffold used to call loadProfile() unconditionally for every target, so a
    // repo with a broken profile file (unrelated to Docusaurus) blocked `lore scaffold docusaurus`
    // even though ConsumerScaffoldOptions.profile is documented as unused by this builder.
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(join(root, ".lore/profile.toml"), "not = [valid");
    const { code, result } = scaffold(["docusaurus"]);
    expect(code).toBe(0);
    expect(result.target).toBe("docusaurus");
  });
});

describe("lore scaffold docusaurus — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file plus a summary", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["docusaurus"], stdout, clock: FIXED_CLOCK });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${WEBSITE_PACKAGE_JSON_REL_PATH}`);
    expect(lines).toContain(`created ${DOCUSAURUS_CONFIG_REL_PATH}`);
    expect(lines).toContain(`created ${SIDEBARS_REL_PATH}`);
    expect(lines).toContain("scaffolded docusaurus config (3 files)");
  });
});

describe("core/consumer-scaffold — buildObsidianScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildObsidianScaffold(opts)).toEqual(buildObsidianScaffold(opts));
  });

  test("plans exactly docs/.obsidian/app.json and docs/.obsidian/.gitignore, and carries the Files & Links guidance notes", () => {
    const plan = buildObsidianScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    // dirs lists every ancestor level (parent before child), matching buildScaffold's own
    // pattern (e.g. ".lore" and ".lore/schemas" as separate entries) — so writeAllOrRollback
    // tracks the implicitly-created "docs" for cleanup, not just the nested ".obsidian" leaf.
    expect(plan.dirs).toEqual(["docs", "docs/.obsidian"]);
    expect(plan.files.map((f) => f.path)).toEqual([OBSIDIAN_APP_JSON_REL_PATH, OBSIDIAN_GITIGNORE_REL_PATH]);
    expect(plan.notes).toEqual(OBSIDIAN_GUIDANCE_NOTES);
  });

  test("app.json carries every documented setting (consumer-compatibility.md §3.2 / ADR-0010 §2)", () => {
    const plan = buildObsidianScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === OBSIDIAN_APP_JSON_REL_PATH)?.contents ?? "";
    expect(raw.endsWith("\n")).toBe(true);
    const config = JSON.parse(raw) as Record<string, unknown>;
    expect(config).toEqual({
      useMarkdownLinks: true,
      newLinkFormat: "relative",
      alwaysUpdateLinks: true,
    });
  });

  test("gitignore excludes everything under docs/.obsidian/ except itself and app.json (LORE-166; consumer-compatibility.md §3.2)", () => {
    // Regression: buildObsidianScaffold used to emit no `.gitignore` at all, despite
    // consumer-compatibility.md §3.2 documenting one — Obsidian's `workspace*.json`/cache files
    // were left untracked-but-not-ignored in a consumer's project. The exclude-all-except pattern
    // (not an enumerated `workspace*.json`/cache list) is a strict superset of that literal
    // wording, matching the pattern this repo's own root .gitignore hand-maintains for its
    // own docs/.obsidian/.
    const plan = buildObsidianScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === OBSIDIAN_GITIGNORE_REL_PATH)?.contents ?? "";
    expect(raw.endsWith("\n")).toBe(true);
    const patternLines = raw.split("\n").filter((line) => line !== "" && !line.startsWith("#"));
    expect(patternLines).toEqual(["*", "!.gitignore", "!app.json"]);
  });

  test("notes is frozen, so a downstream mutation attempt cannot corrupt the shared constant across calls", () => {
    // Regression: OBSIDIAN_GUIDANCE_NOTES used to be returned by reference into every plan, with
    // no copy and no Object.freeze — a single downstream cast-and-mutate (plan.notes is only
    // readonly at compile time) would permanently corrupt the shared constant for every
    // subsequent call in-process (bun test runs all files in one process).
    const first = buildObsidianScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(Object.isFrozen(first.notes)).toBe(true);
    expect(() => (first.notes as string[]).push("injected")).toThrow(TypeError);
    const second = buildObsidianScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(second.notes).toEqual(OBSIDIAN_GUIDANCE_NOTES);
  });
});

describe("lore scaffold obsidian — fresh scaffold", () => {
  test("creates both files and exits 0", () => {
    const { code, result } = scaffold(["obsidian"]);
    expect(code).toBe(0);
    expect(result.target).toBe("obsidian");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: OBSIDIAN_APP_JSON_REL_PATH, action: "created" },
      { path: OBSIDIAN_GITIGNORE_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, OBSIDIAN_APP_JSON_REL_PATH))).toBe(true);
    expect(existsSync(join(root, OBSIDIAN_GITIGNORE_REL_PATH))).toBe(true);
  });

  test("creates the docs/.obsidian directory when the bundle was never initialized", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    scaffold(["obsidian"]);
    expect(existsSync(join(root, OBSIDIAN_APP_JSON_REL_PATH))).toBe(true);
    expect(existsSync(join(root, OBSIDIAN_GITIGNORE_REL_PATH))).toBe(true);
  });
});

describe("lore scaffold obsidian — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["obsidian"]);
    const beforeAppJson = readFileSync(join(root, OBSIDIAN_APP_JSON_REL_PATH), "utf8");
    const beforeGitignore = readFileSync(join(root, OBSIDIAN_GITIGNORE_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["obsidian"], stdout: capture() }),
    );
    expect(err.message).toContain(OBSIDIAN_APP_JSON_REL_PATH);
    expect(err.message).toContain(OBSIDIAN_GITIGNORE_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, OBSIDIAN_APP_JSON_REL_PATH), "utf8")).toBe(beforeAppJson);
    expect(readFileSync(join(root, OBSIDIAN_GITIGNORE_REL_PATH), "utf8")).toBe(beforeGitignore);
  });

  test("--force overwrites both existing files and reports `updated`", () => {
    scaffold(["obsidian"]);
    const { code, result } = scaffold(["obsidian", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files).toEqual([
      { path: OBSIDIAN_APP_JSON_REL_PATH, action: "updated" },
      { path: OBSIDIAN_GITIGNORE_REL_PATH, action: "updated" },
    ]);
  });

  test("a pre-existing non-directory file occupying docs/ is reported as a friendly conflict, not a deep crash (review #2)", () => {
    // Regression: the preflight's blockedDirs check walks plan.dirs, but buildObsidianScaffold
    // used to list only the nested "docs/.obsidian" leaf, never its "docs" ancestor — and
    // existsSync on a path that traverses a non-directory parent returns false, so a plain file
    // sitting at docs/ never tripped the check. It fell through to writeAllOrRollback, which
    // surfaced a lower-level error that never named docs as the blocker and never mentioned
    // --force, unlike every other scaffold conflict (matches docusaurus's own "pre-existing
    // non-directory file occupying website/" regression test).
    writeFileSync(join(root, "docs"), "not a directory\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["obsidian"], stdout: capture() }),
    );
    expect(err.message).toContain("docs");
    // A structural directory blocker is NOT fixed by --force (LORE-238): the hint must not claim
    // it, and must instead direct the user to remove/rename the non-directory entry.
    expect(err.hint).not.toContain("--force");
    expect(err.hint).toContain("remove or rename");
    expect(readFileSync(join(root, "docs"), "utf8")).toBe("not a directory\n");
  });

  test("--force does NOT fix a structural directory blocker and still fails with a conflict (LORE-238)", () => {
    // Regression: --force skips this command's own preflight entirely, so a plain file occupying
    // docs/ is only caught later by writeAllOrRollback -> ensureDir's mkdirSync, which throws
    // EEXIST on the same entry — remapped to a second `conflict`, never a successful overwrite.
    writeFileSync(join(root, "docs"), "not a directory\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["obsidian", "--force"], stdout: capture() }),
    );
    expect(err.type).toBe("conflict");
    expect(readFileSync(join(root, "docs"), "utf8")).toBe("not a directory\n");
  });

  // POSIX-only: a umask-restricted directory doesn't reliably block a nested mkdir on Windows.
  test.skipIf(process.platform === "win32")(
    "a run against a repo with no docs/ rolls back the freshly-created docs/ on a later failure (review #3)",
    () => {
      // Regression: buildObsidianScaffold's plan used to list only the nested leaf "docs/.obsidian",
      // never its parent "docs", so writeAllOrRollback never tracked the implicitly-created docs/
      // for cleanup. A restrictive umask makes the freshly-created docs/ read-only, so the SECOND
      // planned dir (docs/.obsidian) fails to be created inside it — a failure strictly AFTER
      // docs/ was freshly created by this same run — mirroring mkdocs's own "rolls back the
      // freshly-created directory on a later failure" case (test above).
      expect(existsSync(join(root, "docs"))).toBe(false);
      const originalUmask = process.umask(0o222);
      try {
        const err = expectError("denied", () =>
          runScaffold({ root, output: JSON_CTX, args: ["obsidian"], stdout: capture() }),
        );
        expect(err.type).toBe("denied");
      } finally {
        process.umask(originalUmask);
      }
      expect(existsSync(join(root, "docs"))).toBe(false);
    },
  );
});

describe("lore scaffold obsidian — output rendering", () => {
  test("plain mode lists the file, a summary, then the Files & Links guidance notes, in that order", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["obsidian"], stdout, clock: FIXED_CLOCK });
    // Full-sequence equality (not just unordered containment) so a future render() change that
    // prints the notes before or interleaved with the file/summary lines fails this test.
    expect(stdout.lines()).toEqual([
      `created ${OBSIDIAN_APP_JSON_REL_PATH}`,
      `created ${OBSIDIAN_GITIGNORE_REL_PATH}`,
      "scaffolded obsidian config (2 files)",
      ...OBSIDIAN_GUIDANCE_NOTES,
    ]);
  });

  test("the JSON envelope carries the guidance notes verbatim", () => {
    const { result } = scaffold(["obsidian"]);
    expect(result.notes).toEqual(OBSIDIAN_GUIDANCE_NOTES);
  });

  test("mkdocs/docusaurus results carry an empty notes array", () => {
    expect(scaffold(["mkdocs"]).result.notes).toEqual([]);
    expect(scaffold(["docusaurus"]).result.notes).toEqual([]);
  });
});

describe("lore scaffold — argument validation", () => {
  function usageError(args: string[]): LoreError {
    return expectError("usage", () => runScaffold({ root, output: JSON_CTX, args, stdout: capture() }));
  }

  test("no target is a usage error", () => {
    expect(usageError([]).message).toContain("needs a target");
  });

  test("an unknown target is a usage error", () => {
    expect(usageError(["hugo"]).message).toContain('unknown scaffold target "hugo"');
  });

  test("an extra positional is a usage error", () => {
    expect(usageError(["mkdocs", "extra"]).message).toContain('unexpected argument "extra"');
  });

  test("an unknown flag is a usage error", () => {
    expect(usageError(["mkdocs", "--bogus"]).type).toBe("usage");
  });
});

describe("lore scaffold mkdocs — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file plus a summary", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${MKDOCS_CONFIG_REL_PATH}`);
    expect(lines).toContain(`created ${TAGS_INDEX_REL_PATH}`);
    expect(lines).toContain("scaffolded mkdocs config (2 files)");
  });

  test("--json emits the scaffold.result envelope", () => {
    const stdout = capture();
    runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const envelope = JSON.parse(stdout.text()) as { schemaVersion: number; kind: string };
    expect(envelope.schemaVersion).toBe(1);
    expect(envelope.kind).toBe("scaffold.result");
  });
});

describe("lore scaffold mkdocs — a pre-existing custom profile without Reference", () => {
  test("still scaffolds docs/tags.md, without a $schema modeline", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(
      join(root, ".lore/profile.toml"),
      [
        "[profile]",
        'name = "demo"',
        'okf_version = "0.1"',
        "[base.fields]",
        "type = { required = true }",
        "[[types]]",
        'name = "Doc"',
      ].join("\n"),
    );
    const { code } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    const raw = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");
    expect(raw).not.toContain("yaml-language-server");
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
  });

  test("a malformed .lore/profile.toml surfaces as a validation error (exit 6), not a crash", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(join(root, ".lore/profile.toml"), "not = [valid");
    const err = expectError("validation", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.type).toBe("validation");
  });
});
