/**
 * consumer-scaffold.test.ts — `lore scaffold mkdocs` (LORE-39): the additive MkDocs consumer config.
 *
 * AC#1 ("mkdocs build succeeds on the bundle") is exercised end-to-end by the
 * `scaffold-mkdocs` CI job (a real `mkdocs build` against the scaffolded config +
 * this repo's own bundle) — a real Python/MkDocs toolchain is deliberately not a
 * `bun test` dependency (matching the "compile smoke" job's separation for
 * `bun build --compile`). This suite pins the generated bytes and exercises the
 * command's own contract: never-silent-clobber (exit 5 without `--force`), the
 * all-or-nothing pre-flight, and argument validation.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runScaffold, type ScaffoldResult } from "../src/commands/scaffold";
import { parseConcept } from "../src/core/concept";
import { buildMkdocsScaffold, MKDOCS_CONFIG_REL_PATH, TAGS_INDEX_REL_PATH } from "../src/core/consumer-scaffold";
import { LoreError } from "../src/errors";
import type { OutputContext } from "../src/output";
import { capture } from "./helpers";

const JSON_CTX: OutputContext = { mode: "json", color: false };
const PLAIN_CTX: OutputContext = { mode: "plain", color: false };
const FIXED_CLOCK = (): Date => new Date("2026-07-11T12:00:00Z");

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "lore-scaffold-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Run `scaffold` in JSON mode and return the parsed `data` payload plus the exit code. */
function scaffold(args: string[]): { code: number; result: ScaffoldResult } {
  const stdout = capture();
  const code = runScaffold({ root, output: JSON_CTX, args, stdout, clock: FIXED_CLOCK });
  const envelope = JSON.parse(stdout.text()) as { kind: string; data: ScaffoldResult };
  expect(envelope.kind).toBe("scaffold.result");
  return { code, result: envelope.data };
}

/** Assert `fn` throws a {@link LoreError} of `type`, returning it for further assertions. */
function expectError(type: LoreError["type"], fn: () => unknown): LoreError {
  try {
    fn();
  } catch (err) {
    expect(err).toBeInstanceOf(LoreError);
    expect((err as LoreError).type).toBe(type);
    return err as LoreError;
  }
  throw new Error(`expected a ${type} LoreError, but it returned`);
}

describe("core/consumer-scaffold — buildMkdocsScaffold (pure)", () => {
  test("is deterministic: identical options produce identical bytes", () => {
    const opts = { timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" };
    expect(buildMkdocsScaffold(opts)).toEqual(buildMkdocsScaffold(opts));
  });

  test("plans exactly mkdocs.yml (repo root) and docs/tags.md, in that order", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    expect(plan.files.map((f) => f.path)).toEqual([MKDOCS_CONFIG_REL_PATH, TAGS_INDEX_REL_PATH]);
  });

  test("mkdocs.yml carries every documented setting (consumer-compatibility.md §3.3 / ADR-0010 §2)", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "my-project" });
    const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
    expect(yaml).toContain("site_name: my-project");
    expect(yaml).toContain("docs_dir: docs");
    expect(yaml).toContain("name: material");
    expect(yaml).toContain("navigation.indexes");
    expect(yaml).toContain("- search");
    expect(yaml).toContain("- tags");
    expect(yaml).toContain("strict: false");
    expect(yaml).toContain("absolute_links: relative_to_docs");
    expect(yaml).toContain("not_found: warn");
    expect(yaml).toContain("anchors: warn");
    expect(yaml).toContain("omitted_files: ignore");
    expect(yaml).toContain("not_in_nav: |\n  /log.md");
  });

  test("a site name needing escaping is rendered as a safe quoted YAML scalar", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "true" });
    const yaml = plan.files.find((f) => f.path === MKDOCS_CONFIG_REL_PATH)?.contents ?? "";
    expect(yaml).toContain('site_name: "true"');
  });

  test("docs/tags.md is a valid OKF Reference concept carrying the Material tags marker", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-07-11T12:00:00.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
    expect(concept.frontmatter.title).toBe("Tags");
    expect(raw).toContain("<!-- material/tags -->");
  });

  test("stamps docs/tags.md's timestamp from the given option", () => {
    const plan = buildMkdocsScaffold({ timestamp: "2026-01-02T03:04:05.000Z", siteName: "lore" });
    const raw = plan.files.find((f) => f.path === TAGS_INDEX_REL_PATH)?.contents ?? "";
    expect(raw).toContain("timestamp: 2026-01-02T03:04:05.000Z");
  });
});

describe("lore scaffold mkdocs — fresh scaffold", () => {
  test("creates both files and exits 0", () => {
    const { code, result } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    expect(result.target).toBe("mkdocs");
    expect(result.force).toBe(false);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "created" },
      { path: TAGS_INDEX_REL_PATH, action: "created" },
    ]);
    expect(existsSync(join(root, MKDOCS_CONFIG_REL_PATH))).toBe(true);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });

  test("creates the docs/ directory when the bundle was never initialized", () => {
    expect(existsSync(join(root, "docs"))).toBe(false);
    scaffold(["mkdocs"]);
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(true);
  });
});

describe("lore scaffold mkdocs — never-silent-clobber (AC: user-owned, never re-overwritten)", () => {
  test("a re-run without --force refuses with a conflict (exit 5) and touches nothing", () => {
    scaffold(["mkdocs"]);
    const yamlBefore = readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8");
    const tagsBefore = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");

    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.message).toContain(MKDOCS_CONFIG_REL_PATH);
    expect(err.message).toContain(TAGS_INDEX_REL_PATH);
    expect(err.hint).toContain("--force");
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe(yamlBefore);
    expect(readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8")).toBe(tagsBefore);
  });

  test("a hand-authored mkdocs.yml alone (tags.md absent) still refuses without --force", () => {
    writeFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "site_name: hand-authored\n");
    const err = expectError("conflict", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.input).toMatchObject({ paths: [MKDOCS_CONFIG_REL_PATH] });
    expect(readFileSync(join(root, MKDOCS_CONFIG_REL_PATH), "utf8")).toBe("site_name: hand-authored\n");
    expect(existsSync(join(root, TAGS_INDEX_REL_PATH))).toBe(false);
  });

  test("--force overwrites both existing files and reports `updated`", () => {
    scaffold(["mkdocs"]);
    const { code, result } = scaffold(["mkdocs", "--force"]);
    expect(code).toBe(0);
    expect(result.force).toBe(true);
    expect(result.files).toEqual([
      { path: MKDOCS_CONFIG_REL_PATH, action: "updated" },
      { path: TAGS_INDEX_REL_PATH, action: "updated" },
    ]);
  });

  test("--force on a fresh repo still reports `created` (not `updated`)", () => {
    const { result } = scaffold(["mkdocs", "--force"]);
    expect(result.files.every((f) => f.action === "created")).toBe(true);
  });
});

describe("lore scaffold — argument validation", () => {
  function usageError(args: string[]): LoreError {
    return expectError("usage", () => runScaffold({ root, output: JSON_CTX, args, stdout: capture() }));
  }

  test("no target is a usage error", () => {
    expect(usageError([]).message).toContain("needs a target");
  });

  test("an unknown target is a usage error", () => {
    expect(usageError(["hugo"]).message).toContain('unknown scaffold target "hugo"');
  });

  test("a documented-but-unimplemented target (docusaurus/obsidian) is a usage error, not a crash", () => {
    expect(usageError(["docusaurus"]).message).toContain("not implemented yet");
    expect(usageError(["obsidian"]).message).toContain("not implemented yet");
  });

  test("an extra positional is a usage error", () => {
    expect(usageError(["mkdocs", "extra"]).message).toContain('unexpected argument "extra"');
  });

  test("an unknown flag is a usage error", () => {
    expect(usageError(["mkdocs", "--bogus"]).type).toBe("usage");
  });
});

describe("lore scaffold mkdocs — output rendering", () => {
  test("plain mode lists one `<action> <path>` line per file plus a summary", () => {
    const stdout = capture();
    runScaffold({ root, output: PLAIN_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const lines = stdout.lines();
    expect(lines).toContain(`created ${MKDOCS_CONFIG_REL_PATH}`);
    expect(lines).toContain(`created ${TAGS_INDEX_REL_PATH}`);
    expect(lines).toContain("scaffolded mkdocs config (2 files)");
  });

  test("--json emits the scaffold.result envelope", () => {
    const stdout = capture();
    runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout, clock: FIXED_CLOCK });
    const envelope = JSON.parse(stdout.text()) as { schemaVersion: number; kind: string };
    expect(envelope.schemaVersion).toBe(1);
    expect(envelope.kind).toBe("scaffold.result");
  });
});

describe("lore scaffold mkdocs — a pre-existing custom profile without Reference", () => {
  test("still scaffolds docs/tags.md, without a $schema modeline", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(
      join(root, ".lore/profile.toml"),
      [
        "[profile]",
        'name = "demo"',
        'okf_version = "0.1"',
        "[base.fields]",
        "type = { required = true }",
        "[[types]]",
        'name = "Doc"',
      ].join("\n"),
    );
    const { code } = scaffold(["mkdocs"]);
    expect(code).toBe(0);
    const raw = readFileSync(join(root, TAGS_INDEX_REL_PATH), "utf8");
    expect(raw).not.toContain("yaml-language-server");
    const concept = parseConcept(TAGS_INDEX_REL_PATH, raw);
    expect(concept.type).toBe("Reference");
  });

  test("a malformed .lore/profile.toml surfaces as a validation error (exit 6), not a crash", () => {
    mkdirSync(join(root, ".lore"), { recursive: true });
    writeFileSync(join(root, ".lore/profile.toml"), "not = [valid");
    const err = expectError("validation", () =>
      runScaffold({ root, output: JSON_CTX, args: ["mkdocs"], stdout: capture() }),
    );
    expect(err.type).toBe("validation");
  });
});
