import type { BridgeAction, BridgeFilePlan, BridgePlan } from "./agent-bridge";

/**
 * Google's own official documentation (antigravity.google/docs/cli/best-practices/) names
 * `GEMINI.md` and `AGENTS.md` as two equally official, parallel workspace-root files Antigravity
 * reads at startup — not primary/fallback. Gemini CLI reads the same filename (geminicli.com/docs/
 * cli/gemini-md/), so this bridge serves both tools rather than Antigravity alone (LCLI-464).
 *
 * `GEMINI.md` has no skill-file equivalent (unlike Claude Code/Codex's SKILL.md bridges), so this
 * mirrors {@link "./hermes-bridge".planHermesBridge} exactly: one plain nudge file, no directory
 * scaffold, no credentials read or written.
 */
export const GEMINI_MD_REL_PATH = "GEMINI.md";

export function buildGeminiContextDoc(): string {
  return `# Lore — OKF documentation CLI

This project uses **lore** for the OKF documentation bundle under \`docs/\`.

- Run \`lore instructions\` before documentation work and pull the needed topic instructions.
- Use Lore commands for managed links, moves, and synchronization; do not hand-edit managed blocks.
- Follow the repository's Backlog workflow independently.
- This is project-local Antigravity/Gemini CLI context only. It does not configure either tool
  globally or contain credentials.

<!-- Generated by \`lore init --antigravity\`; do not hand-edit. -->
`;
}

export interface PlanAntigravityBridgeInput {
  readonly contextOnDisk: string | null;
  readonly force: boolean;
  readonly check: boolean;
}

export function planAntigravityBridge(input: PlanAntigravityBridgeInput): BridgePlan {
  const desired = buildGeminiContextDoc();
  const file = planContext(input, desired);
  return { files: [file] };
}

function planContext(input: PlanAntigravityBridgeInput, desired: string): BridgeFilePlan {
  if (input.contextOnDisk === null) return { path: GEMINI_MD_REL_PATH, action: "created", contents: desired };
  if (input.contextOnDisk === desired) return { path: GEMINI_MD_REL_PATH, action: "unchanged", contents: null };
  const action: BridgeAction = input.force && !input.check ? "updated" : "protected";
  return { path: GEMINI_MD_REL_PATH, action, contents: action === "updated" ? desired : null };
}
