import {
  type BridgeAction,
  type BridgeFilePlan,
  type BridgePlan,
  instructionTopicKeys,
  withGovernance,
} from "./agent-bridge";
import { upsertManagedBlock } from "./managed-block";

export const CODEX_SKILL_REL_PATH = ".codex/skills/lore/SKILL.md";
export const AGENTS_MD_REL_PATH = "AGENTS.md";
export const CODEX_AGENT_BLOCK_LABEL = "lore:agents";

export function buildCodexSkillDoc(): string {
  return `---
name: lore
description: Author, retrieve, and maintain OKF documentation with the Lore CLI, including explicit multi-repository workspaces. Use whenever Codex reads, writes, links, moves, queries, synchronizes, validates, or checks documentation so Story/Task coupling, managed blocks, provenance, and cross-links remain coherent. Run \`lore instructions\` for the canonical agent loop and its topic subcommands for just-in-time details.
---

# Lore — OKF documentation CLI

Use \`lore\` as this repository's deterministic, CLI-first documentation engine. Treat
\`lore instructions\` as the source of truth; this skill is the Codex discovery bridge.

\`lore link\`, \`lore unlink\`, \`lore rename\`, and \`lore sync\` commit tracker files only when the
configured tracker is Backlog; Quest and Jira keep their own storage. Check the repository's own
instructions for any commit-authority rule before running them.

## Start

1. Run \`lore instructions\`.
2. Choose owner-local scope or an explicit workspace; pull \`lore instructions workspace\` for
   cross-repository questions.
3. Find what you need with \`lore query "<words>" --limit 5\`, then \`lore read <id>\` for the best
   hit; do not browse \`docs/index.md\` or grep \`docs/\` first. Inspect the coupled task status.
4. Pull only the needed topic instructions: ${instructionTopicKeys()}.
5. Author prose only outside Lore-managed regions.
6. After documentation changes, run \`lore sync\`, \`lore validate --strict\`,
   \`lore check --strict\`, and \`git diff --check\`.

## Guardrails

- Use \`lore new\` to create typed concepts.
- Use \`lore link\` and \`lore unlink\` for Story/Task coupling.
- Use \`lore rename\`, \`lore replace\`, and \`lore supersede\` instead of manually rewriting
  managed references.
- Do not hand-edit Lore-managed blocks, generated indexes, or generated logs.
- Follow the repository's tracker workflow independently; Lore does not replace the tracker's own
  task lifecycle commands.
- Use \`--workspace <manifest>\` only for explicit cross-repository reads. Qualify workspace IDs as
  \`<member-id>::<source-id>\`, preserve returned provenance, and bound retrieval with repository,
  depth, result, edge, and token filters.
- Prefer \`--json\` for machine-stable output and \`--plain\` for readable output. Branch on exit
  codes: \`0\` success, \`2\` usage, \`3\` not found, \`4\` denied, \`5\` conflict, \`6\`
  validation/drift, \`7\` indeterminate (cannot judge from here; never auto-repair).

## Command map

- Authoring: \`new\`, \`replace\`, \`rename\`, \`supersede\`
- Coupling and reconciliation: \`link\`, \`unlink\`, \`sync\`, \`tasks\`, \`orphans\`
- Verification: \`validate\`, \`check\`
- Discovery and context: \`query\`, \`read\`, \`context\`, \`agent\`, \`graph\`, \`path\`, \`impact\`,
  \`snapshot\`, \`changed\`, \`provenance\`, \`explorer\`, \`instructions\`
- Interchange and setup: \`export\`, \`schema\`, \`types\`, \`scaffold\`, \`backlog\`, \`agents\`

## Optional task-scoped context

When native Codex developer instructions name a committed Lore profile, use this stable opt-in line:

> Lore profile: \`<name>\`. Before working, run \`lore agent context <name> --task "<assigned task>"\`
> and ground decisions in the returned source IDs.

Lore supplies evidence only. It does not create or patch native agents, prompts, tools, models,
permissions, or execution settings.

<!-- Generated by \`lore init --codex\`; do not hand-edit. -->
`;
}

/**
 * The `AGENTS.md` nudge body. `governance` is the Constitution core and Constants pointer
 * (LCLI-597, OPAG-425 R8), appended exactly as the `CLAUDE.md` nudge appends it
 * ({@link withGovernance}); empty leaves the body byte-identical to what it was before R8.
 */
export function buildCodexNudgeBody(governance: readonly string[] = []): string {
  return withGovernance(
    `This repo uses **lore** — an OKF-native documentation CLI — for the docs bundle under \`docs/\`.
When working on documentation, drive it through \`lore\` (not a plain editor) so Story <-> Task
coupling, managed blocks, and cross-links stay coherent.

- **Find and read docs:** \`lore query "<words>" --limit 5\`, then \`lore read <id>\` for the best hit.
- **Skill:** \`${CODEX_SKILL_REL_PATH}\` — how to drive lore.
- **Just-in-time detail:** run \`lore instructions\` for the canonical agent loop, then
  \`lore instructions <topic>\` (${instructionTopicKeys()}).`,
    governance,
  );
}

export interface PlanCodexBridgeInput {
  readonly skillOnDisk: string | null;
  readonly agentsOnDisk: string | null;
  readonly force: boolean;
  readonly check: boolean;
  /** The Constitution core and Constants pointer lines (LCLI-597); see {@link buildCodexNudgeBody}. */
  readonly governance?: readonly string[];
}

export function planCodexBridge(input: PlanCodexBridgeInput): BridgePlan {
  return { files: [planSkill(input), planNudge(input)] };
}

function planSkill(input: PlanCodexBridgeInput): BridgeFilePlan {
  const desired = buildCodexSkillDoc();
  if (input.skillOnDisk === null) return { path: CODEX_SKILL_REL_PATH, action: "created", contents: desired };
  if (input.skillOnDisk === desired) return { path: CODEX_SKILL_REL_PATH, action: "unchanged", contents: null };
  const action: BridgeAction = input.force && !input.check ? "updated" : "protected";
  return { path: CODEX_SKILL_REL_PATH, action, contents: action === "updated" ? desired : null };
}

function planNudge(input: PlanCodexBridgeInput): BridgeFilePlan {
  const desired = upsertManagedBlock(input.agentsOnDisk ?? "", {
    label: CODEX_AGENT_BLOCK_LABEL,
    body: buildCodexNudgeBody(input.governance),
  });
  if (input.agentsOnDisk === null) return { path: AGENTS_MD_REL_PATH, action: "created", contents: desired };
  if (input.agentsOnDisk === desired) return { path: AGENTS_MD_REL_PATH, action: "unchanged", contents: null };
  return { path: AGENTS_MD_REL_PATH, action: "updated", contents: desired };
}
