import type { BridgeAction, BridgeFilePlan, BridgePlan } from "./agent-bridge";

/**
 * Hermes' official context-file documentation gives project-local `.hermes.md`
 * precedence over AGENTS.md. This bridge therefore writes only that local file:
 * it never reads or writes ~/.hermes/config.yaml, ~/.hermes/.env, or credentials.
 */
export const HERMES_CONTEXT_REL_PATH = ".hermes.md";

export function buildHermesContextDoc(): string {
  return `# Lore — OKF documentation CLI

This project uses **lore** for the OKF documentation bundle under \`docs/\`.

- Run \`lore instructions\` before documentation work and pull the needed topic instructions.
- Use Lore commands for managed links, moves, and synchronization; do not hand-edit managed blocks.
- Follow the repository's Backlog workflow independently.
- This is project-local Hermes context only. It does not configure Hermes globally or contain credentials.

<!-- Generated by \`lore init --hermes\`; do not hand-edit. -->
`;
}

export interface PlanHermesBridgeInput {
  readonly contextOnDisk: string | null;
  readonly force: boolean;
  readonly check: boolean;
}

export function planHermesBridge(input: PlanHermesBridgeInput): BridgePlan {
  const desired = buildHermesContextDoc();
  const file = planContext(input, desired);
  return { files: [file] };
}

function planContext(input: PlanHermesBridgeInput, desired: string): BridgeFilePlan {
  if (input.contextOnDisk === null) return { path: HERMES_CONTEXT_REL_PATH, action: "created", contents: desired };
  if (input.contextOnDisk === desired) return { path: HERMES_CONTEXT_REL_PATH, action: "unchanged", contents: null };
  const action: BridgeAction = input.force && !input.check ? "updated" : "protected";
  return { path: HERMES_CONTEXT_REL_PATH, action, contents: action === "updated" ? desired : null };
}
