/**
 * log.ts — the bundle's `log.md` as a **git-history-derived**, byte-stable artifact (LORE-47).
 *
 * Where `index.md` is regenerated from the bundle graph, `log.md` is a folder-sectioned change log
 * derived from the repository's own commit history. Each commit appears exactly once, assigned to
 * the deepest common bundle folder it touched. This module owns two things:
 *
 * - **The `GitAdapter` seam** — the *third* injectable deterministic seam, alongside the clock
 *   and the Backlog subprocess (lore-design §8; [ADR-0014](../../docs/adr/0014-core-has-no-llm-dependency.md)).
 *   git is *local, deterministic computation* — not a network model — so reading history over a
 *   **pinned commit range** is reproducible, offline-safe, and air-gap-safe. Core depends only on
 *   the interface; the real adapter that shells `git log` is impure command-layer wiring (the same
 *   boundary the real `() => new Date()` clock sits on), supplied where `lore sync` is built. Tests
 *   inject a fake adapter returning a fixed fake history, never real `git`.
 *
 * - **The pure `generateLog`** — given a set of {@link GitCommit}s, produce the exact `log.md`
 *   bytes. It is total and order-independent: folders are directory-sorted and the commits under
 *   each are sorted by `(timestamp, hash)`, so the same history always yields byte-identical output
 *   (idempotent) regardless of the order the adapter returned commits in (lore-design §8: directory
 *   walks are sorted; no nondeterminism in core).
 *
 * **Regeneration merges; it never replaces (LCLI-474).** The visible history is not always a superset
 * of what the committed `log.md` records. A rewritten history, a shallow clone, a grafted history, or
 * a depth-limited CI checkout all present a history that is a strict *subset*, and a replace would
 * silently destroy every entry behind a commit that is no longer reachable — for which the committed
 * file is then the only surviving record. So {@link generateLog} takes the committed bytes as
 * {@link GenerateLogOptions.existing}, and its output is a **superset**: derived entries render from
 * the history, and any committed entry the history can no longer account for is carried forward under
 * the folder it was recorded in. When history only grows — the normal case — every committed entry is
 * re-derived, nothing is carried forward, and the output is byte-identical to what a replace produced.
 *
 * Two consequences, both deliberate rather than incidental:
 *
 * - **A rewritten commit appears twice** (once under its old hash, once under its new), because the
 *   two are indistinguishable from two genuine commits. A log of history that over-reports is
 *   recoverable by reading it; one that under-reports is not, so the superset is the honest side to
 *   err on.
 * - **Carried-forward entries are emitted verbatim**, never re-rendered. Re-rendering would feed an
 *   already-{@link renderSubject}ed subject back through the same escape and grow its code-span
 *   delimiter on every sync — output that is a superset but no longer byte-stable.
 *
 * **The merge reports itself (LCLI-485).** Carrying entries forward silently is only half the fix:
 * anything in the committed file that is *not* a folder heading or an entry line — hand-authored
 * prose, a note pasted under the title, an entry whose heading was deleted — is not representable in
 * the regenerated bytes and is lost on the next sync. That loss used to be discoverable only by
 * diffing. So {@link generateLogWithStats} returns, alongside the bytes, a {@link LogMergeStats}:
 * how many entries were added, how many were carried forward, and how many lines could not be kept.
 * The bytes are unchanged by this — the accounting is a side channel, and `generateLog` still
 * returns exactly the string it always did.
 *
 * **Drift-gate exemption (ADR-0007).** Because a git-derived `log.md` changes on *every* commit, it
 * is materialized at **`lore sync`** time and **excluded** from `lore check`'s regenerate-and-compare
 * drift gate. Gating it would report permanent drift (the gate's own commit would invalidate it) and
 * break on shallow/read-only CI checkouts where full history is absent. `index.md` and the
 * `<!-- lore:tasks -->` managed blocks stay gated as before. The exemption is what made the loss above
 * invisible, and it still stands — but it no longer hides anything, because merge semantics make a
 * shrinking `log.md` impossible by construction, which is a stronger guarantee than a gate reporting
 * one after the fact.
 *
 * Per the core contract (lore-design §2.1) this module is pure: no filesystem, no spawn, no clock.
 */

import { posix } from "node:path";
import { singleLine } from "../errors";
import { compareCodeUnits } from "./order";
import { DOCS_DIR } from "./scaffold";

/**
 * One commit as the {@link GitAdapter} surfaces it — the minimal, deterministic projection
 * `generateLog` needs. All fields are stable for a given commit in a given repository.
 */
export interface GitCommit {
  /** The commit hash (full or a stable abbreviation). Emitted verbatim and used as the sort tiebreak. */
  readonly hash: string;
  /** The committer date as an ISO-8601 string with offset (never a `Date`, mirroring ADR-0006 §2). */
  readonly timestamp: string;
  /** The commit message's first line (subject). Treated as single-line; any stray newline is collapsed. */
  readonly subject: string;
  /** The repo-relative POSIX paths the commit touched (in any order; `generateLog` groups + sorts). */
  readonly files: readonly string[];
}

/**
 * A **pinned** commit range — the determinism boundary. `to` is the inclusive upper bound (a tag
 * or sha, e.g. `HEAD` resolved to a sha by the caller); `from`, when given, is the exclusive lower
 * bound. Pinning both ends is what makes a generated `log.md` reproducible: the same range over the
 * same repository yields the same commits.
 */
export interface GitLogRange {
  /** Exclusive lower bound (a tag/sha); absent → from the start of history. */
  readonly from?: string;
  /** Inclusive upper bound (a tag/sha) — pin this to a concrete sha for a reproducible log. */
  readonly to: string;
}

/**
 * The injectable git seam (lore-design §8, the third after clock + Backlog). The real
 * implementation shells `git log` and lives at the command layer (impure, like the real clock);
 * tests inject a fake returning a fixed fake history. Core knows only this interface.
 */
export interface GitAdapter {
  /**
   * The commits touching `root` within `range`, in any order. `root` is a **pathspec**, not a
   * post-filter hint: an implementation is expected to scope the underlying `git log` walk itself
   * (e.g. `-- docs`) so a commit that never touched anything under `root` is never even considered,
   * let alone returned — the real adapter (`adapters/git.ts`) does exactly that, so `lore sync`
   * never walks or buffers unrelated repository history just to build a docs-scoped `log.md`.
   * Optional only so a fake ignoring it stays a one-liner; {@link buildLog} always passes it.
   */
  history(range: GitLogRange, root?: string): readonly GitCommit[];
}

/** Options for {@link generateLog}. */
export interface GenerateLogOptions {
  /**
   * The bundle root the log is scoped to (default {@link DOCS_DIR}, `"docs"`). A commit's files
   * outside this root are ignored, so `log.md` reflects bundle history, not unrelated source churn.
   * Compared by path segment, so `"docs"` matches `docs/x.md` but never a sibling like `docsite/x.md`.
   * An empty string falls back to the default (an empty root would match nothing).
   */
  readonly root?: string;
  /** The document's top-level heading (default `"Change log"`). */
  readonly title?: string;
  /**
   * The **committed** `log.md` bytes, when the bundle already has one. Entries in it that `commits`
   * cannot account for are carried forward rather than dropped, so regeneration is a merge and never
   * loses history lore can no longer see (see the module header). Absent or empty — a bundle with no
   * committed log — regeneration is simply the derived set. Parsing is **total**: only well-formed
   * `## <folder>` headings and `- <timestamp> <hash> <subject>` entry lines are recognized, and every
   * other line is ignored rather than throwing, so a hand-edited or truncated file degrades to
   * "preserve the entries I can still read" instead of failing the sync. Ignored is not unreported:
   * every line that is neither structure nor a legible entry is counted into
   * {@link LogMergeStats.dropped} so the caller can say so (LCLI-485).
   */
  readonly existing?: string;
}

/**
 * What one regeneration did to the committed log — the diagnostic side channel of
 * {@link generateLogWithStats} (LCLI-485). Every field is an accounting of the *merge*, never of the
 * bytes: the same commits and the same committed file always produce the same output regardless of
 * whether anyone reads these numbers.
 */
export interface LogMergeStats {
  /** Entries derived from the visible history that the committed log did not already record. */
  readonly added: number;
  /** Committed entries the visible history can no longer account for, preserved by the merge. */
  readonly carriedForward: number;
  /**
   * Lines of the committed log that regeneration cannot preserve — prose, a malformed entry, an
   * entry line with no folder heading above it, a folder heading holding no entries. Zero for every
   * log lore itself generated, which is what makes a nonzero value worth reporting.
   */
  readonly dropped: number;
  /**
   * Up to {@link DROPPED_SAMPLE_LIMIT} of those lines, verbatim, so a caller's warning can show what
   * is being lost and not only how much. Bounded on purpose: a pathologically hand-edited file must
   * not be able to grow a diagnostic without limit (cli-contract §3).
   */
  readonly droppedSamples: readonly string[];
}

/** The bytes plus the accounting — what {@link generateLogWithStats} returns. */
export interface LogRegeneration {
  /** The `log.md` bytes, byte-identical to what {@link generateLog} returns for the same inputs. */
  readonly bytes: string;
  /** What the merge did to get there. */
  readonly stats: LogMergeStats;
}

/** How many dropped lines {@link LogMergeStats.droppedSamples} keeps (see that field). */
const DROPPED_SAMPLE_LIMIT = 3;

/** One commit as it renders in `log.md` — the commit's identity plus its subject collapsed once. */
interface LogEntry {
  readonly hash: string;
  readonly timestamp: string;
  readonly subject: string;
  /**
   * The subject exactly as it appears on the rendered entry line — {@link renderSubject} applied for
   * a derived commit, and the committed bytes verbatim for a carried-forward one. Kept separate from
   * {@link subject} so a carried-forward entry is never re-escaped (module header).
   */
  readonly rendered: string;
  /**
   * The absolute instant the {@link timestamp} denotes (epoch ms), or `NaN` when it carries no
   * explicit offset (so a host-local — machine-dependent — parse is never trusted) or is
   * unparseable. Computed once at construction so {@link compareEntries} parses each commit's
   * timestamp **once** total, not O(N log N) times inside the sort comparator.
   */
  readonly instant: number;
}

/**
 * Build a `log.md`'s bytes from a {@link GitAdapter} over a pinned range — the function `lore sync`
 * calls with the real adapter and tests call with a fake one, so the seam is exercised end-to-end.
 * The same resolved `root` that scopes `log.md`'s content is also passed to `adapter.history` as a
 * pathspec, so the real adapter can scope the underlying `git log` walk itself — not just the
 * `generateLog` grouping below — to the bundle root (LORE-143). The pure {@link generateLog} does
 * the byte computation; this only resolves the history through the seam.
 */
export function buildLog(adapter: GitAdapter, range: GitLogRange, options: GenerateLogOptions = {}): string {
  return buildLogWithStats(adapter, range, options).bytes;
}

/**
 * {@link buildLog} with the merge accounting `lore sync` reports (LCLI-485). The bytes are the same
 * bytes; only the extra {@link LogMergeStats} distinguishes this from the call above.
 */
export function buildLogWithStats(
  adapter: GitAdapter,
  range: GitLogRange,
  options: GenerateLogOptions = {},
): LogRegeneration {
  return generateLogWithStats(adapter.history(range, resolveRoot(options.root)), options);
}

/**
 * Render the byte-stable `log.md` for `commits`: assign each commit to the deepest common bundle
 * folder of its touched files, emit folders in directory-sorted order, and under each folder list
 * its commits sorted by `(timestamp, hash)`. The single deterministic folder assignment keeps one
 * rendered entry per commit even when a change spans multiple folders.
 *
 * Pure, total, and order-independent — the same set of commits always produces byte-identical
 * output, so re-running `lore sync` with no new history is a byte-level no-op. A commit that touched
 * no file under the bundle root contributes nothing (it never appears). An empty history yields just
 * the heading, so the file is always well-formed.
 */
export function generateLog(commits: readonly GitCommit[], options: GenerateLogOptions = {}): string {
  return generateLogWithStats(commits, options).bytes;
}

/**
 * {@link generateLog} plus the merge accounting (LCLI-485): the identical bytes, and a
 * {@link LogMergeStats} saying how many entries this regeneration added, how many it carried forward
 * from the committed file, and how many committed lines it could not keep. The counts are derived
 * from the same single pass that produces the bytes, so they can never disagree with the file that
 * was actually written.
 */
export function generateLogWithStats(commits: readonly GitCommit[], options: GenerateLogOptions = {}): LogRegeneration {
  const root = resolveRoot(options.root);
  const title = options.title ?? "Change log";

  // folder → the commits assigned to it. A commit spanning several folders is assigned only to
  // their deepest common folder, so every section truthfully contains all of its touched paths and
  // no rendered entry is duplicated. Two genuinely distinct commits sharing an abbreviated hash
  // remain distinct. The subject is collapsed once per commit.
  const byFolder = new Map<string, LogEntry[]>();
  const place = (folder: string, entry: LogEntry): void => {
    const bucket = byFolder.get(folder);
    if (bucket === undefined) {
      byFolder.set(folder, [entry]);
    } else {
      bucket.push(entry);
    }
  };

  // Parsed up front so the derived loop below can tell an entry the committed log already recorded
  // from one this sync is adding. It is a pure read of `options.existing`; moving it ahead of the
  // derived loop changes no bucket, no sort, and no byte.
  const parsed = parseEntries(options.existing);
  const committed = new Set(parsed.entries.map(([, entry]) => identity(entry.timestamp, entry.hash)));

  // Derived entries are placed first and are never de-duplicated against each other, so the
  // abbreviated-hash contract above still holds exactly as it did before the merge existed.
  const derived = new Set<string>();
  let added = 0;
  for (const commit of commits) {
    const folder = commonFolder(foldersTouched(commit.files, root));
    if (folder === undefined) {
      continue;
    }
    const subject = singleLine(commit.subject);
    const key = identity(commit.timestamp, commit.hash);
    // "Added" is what this sync contributes that the committed file did not already hold, so a
    // re-sync over unchanged history reports 0 rather than re-announcing the whole log. A commit
    // seen twice in one history counts once; it still renders once.
    if (!derived.has(key) && !committed.has(key)) {
      added += 1;
    }
    derived.add(key);
    place(folder, {
      hash: commit.hash,
      timestamp: commit.timestamp,
      subject,
      rendered: renderSubject(subject),
      instant: toInstant(commit.timestamp),
    });
  }

  // What survives this filter is exactly the set the visible history can no longer account for —
  // the set a replace would have destroyed (see the module header).
  const carried = new Set<string>();
  for (const [folder, entry] of parsed.entries) {
    const key = identity(entry.timestamp, entry.hash);
    if (derived.has(key) || carried.has(key)) {
      continue;
    }
    carried.add(key);
    place(folder, entry);
  }

  const sections = [...byFolder.entries()]
    .sort(([a], [b]) => compareCodeUnits(a, b))
    .map(([folder, entries]) => {
      const lines = entries.sort(compareEntries).map((e) => `- ${e.timestamp} ${e.hash} ${e.rendered}`);
      return `## ${folder}\n\n${lines.join("\n")}\n`;
    });

  return {
    bytes: [`# ${title}\n`, ...sections].join("\n"),
    stats: {
      added,
      carriedForward: carried.size,
      dropped: parsed.dropped.length,
      droppedSamples: parsed.dropped.slice(0, DROPPED_SAMPLE_LIMIT),
    },
  };
}

/**
 * A commit's identity for merge purposes: `(timestamp, hash)`. The hash alone is not enough — it may
 * be an abbreviation, and {@link generateLog} contractually keeps two distinct commits that share one
 * distinct. Pairing it with the committer timestamp makes a false match require two commits sharing
 * both an abbreviated hash and an exact instant. The *subject* is deliberately not part of the key:
 * an entry written by an older lore whose subject rendered differently is still the same commit, and
 * keying on it would carry that entry forward as a duplicate of one already derived.
 */
function identity(timestamp: string, hash: string): string {
  return `${timestamp}\u0000${hash}`;
}

/** Matches a `log.md` folder section heading — `## docs/adr`. */
const FOLDER_HEADING = /^## (\S.*)$/;

/** Matches a rendered `log.md` entry line — `- <timestamp> <hash> <subject>`, subject possibly empty. */
const LOG_ENTRY = /^- (\S+) (\S+)(?: (.*))?$/;

/** Matches the generated document title — the single level-1 ATX heading `generateLog` emits first. */
const TITLE_HEADING = /^# \S/;

/** What {@link parseEntries} read out of a committed `log.md`: the legible entries, and the rest. */
interface ParsedLog {
  /** Every legible entry, paired with the folder heading it was recorded under. */
  readonly entries: readonly (readonly [string, LogEntry])[];
  /**
   * Every line regeneration cannot preserve, verbatim (see {@link isStructural}). In document order,
   * except that a folder heading is held back until its section closes, so it trails the lines it
   * introduced rather than preceding them.
   */
  readonly dropped: readonly string[];
}

/**
 * Whether `line` is **structure** of a generated `log.md` rather than content — the only two shapes
 * {@link generateLog} emits besides a folder heading and an entry line, and therefore the only two a
 * dropped-content report must stay silent about.
 *
 * This predicate is the whole difference between a warning worth reading and one nobody reads.
 * {@link parseEntries} skips blank lines, the title, and genuinely lost prose through the same
 * `continue`, so a report that counted "everything skipped" would fire on **every sync of every
 * healthy bundle**: `generateLog` writes the title, a blank line after it, a blank between sections,
 * and a trailing newline that yields one more blank when the file is split. A warning that always
 * fires teaches its reader to ignore it, which is strictly worse than not warning at all — the
 * defect this reporting exists for (a consumer's prose silently disappearing) would then be
 * invisible *and* accompanied by a warning everyone had learned to skip past.
 *
 * - A **blank** line. Whitespace-only counts too: it carries no content, so reporting an editor's
 *   stray trailing spaces as lost prose would be a false alarm over nothing a reader could act on.
 * - The **title** — a level-1 ATX heading (`# Change log`, or whatever `options.title` set). A
 *   generated log has exactly one, on its first line, but *any* level-1 heading is treated as a
 *   title rather than only the first line: under-reporting an extra hand-authored `#` heading is the
 *   cheap mistake here and crying wolf on every sync is the expensive one.
 *
 * Everything else is content the regenerated file will not contain, and is reported.
 */
function isStructural(line: string): boolean {
  return line.trim() === "" || TITLE_HEADING.test(line);
}

/**
 * Parse a committed `log.md` back into `(folder, entry)` pairs — the inverse of the rendering in
 * {@link generateLog}, and the input to its merge.
 *
 * **Total by construction**: it never throws and never rejects a document. A line that is neither a
 * folder heading nor an entry — prose, a stray hand edit, the `# Change log` title, a blank — is
 * skipped, as is any entry line appearing before the first heading (it has no folder to belong to).
 * A malformed file therefore degrades to "carry forward the entries still legible in it", which is
 * the failure direction that loses nothing; the alternative, failing the sync, would leave a
 * repository unable to run `lore sync` at all because of a file lore itself generated.
 *
 * Total is not the same as silent (LCLI-485): every line it skips that is not {@link isStructural}
 * structure is collected into {@link ParsedLog.dropped}, so the caller can report the loss it cannot
 * prevent. A folder heading is collected too when its section yields no entry at all — a generated
 * log never emits an empty section, so such a heading is hand-authored structure that regeneration
 * will not reproduce either.
 *
 * Subjects are taken **verbatim**, not re-parsed out of their {@link renderSubject} escaping, so a
 * carried-forward entry re-renders to the identical bytes it was read from (module header).
 *
 * **A trailing `\r` is stripped before matching**, so a CRLF working copy — the default for a git
 * checkout on Windows with `core.autocrlf=true` — parses identically to an LF one. This is not a
 * cosmetic detail: JavaScript's `$` (without the `m` flag) matches only at end of input or before a
 * final `\n`, never before a `\r`, so on CRLF bytes *neither* pattern below would match a single
 * line. The parse would silently yield nothing, the merge would carry nothing forward, and
 * regeneration would degrade back to exactly the replace semantics this module exists to prevent —
 * on one platform, with every test still green, because fixtures are written with `\n`.
 */
function parseEntries(existing: string | undefined): ParsedLog {
  if (existing === undefined || existing === "") {
    return { entries: [], dropped: [] };
  }

  const entries: (readonly [string, LogEntry])[] = [];
  const dropped: string[] = [];
  let folder: string | undefined;
  // The most recent folder heading whose section has not yet yielded an entry, held rather than
  // reported until the section closes (the next heading, or end of file).
  let emptySection: string | undefined;
  for (const rawLine of existing.split("\n")) {
    const line = rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine;
    const heading = FOLDER_HEADING.exec(line);
    if (heading !== null) {
      if (emptySection !== undefined) {
        dropped.push(emptySection);
      }
      folder = (heading[1] ?? "").trim();
      emptySection = line;
      continue;
    }
    const entry = LOG_ENTRY.exec(line);
    const timestamp = entry?.[1];
    const hash = entry?.[2];
    if (folder === undefined || folder === "" || timestamp === undefined || hash === undefined) {
      // Note this also catches a *well-formed* entry line with no folder heading above it: it has no
      // section to belong to, so it is as lost as the prose beside it and is reported the same way.
      if (!isStructural(line)) {
        dropped.push(line);
      }
      continue;
    }
    emptySection = undefined;
    const rendered = entry?.[3] ?? "";
    entries.push([folder, { hash, timestamp, subject: rendered, rendered, instant: toInstant(timestamp) }]);
  }
  if (emptySection !== undefined) {
    dropped.push(emptySection);
  }
  return { entries, dropped };
}

/**
 * Render a commit subject without letting git history create prose that lore's own MDX portability
 * check rejects. Ordinary subjects stay byte-identical. A subject containing one of the two raw
 * characters MDX interprets specially (`<` for JSX/HTML and `{` for an expression) becomes a
 * CommonMark code span, which presents a commit subject as literal text and is deliberately outside
 * the portability scanner's prose walk.
 *
 * The delimiter is one backtick longer than the subject's longest backtick run, so even a commit
 * subject that already contains inline-code-looking text remains one well-formed code span. Padding
 * the content with one space follows CommonMark's code-span normalization and preserves the visible
 * subject without requiring any lossy character replacement.
 */
function renderSubject(subject: string): string {
  if (!/[<{]/.test(subject)) {
    return subject;
  }

  const longestBacktickRun = Math.max(0, ...(subject.match(/`+/g)?.map((run) => run.length) ?? []));
  const delimiter = "`".repeat(longestBacktickRun + 1);
  return `${delimiter} ${subject} ${delimiter}`;
}

/**
 * Normalize a {@link GenerateLogOptions.root}/{@link GitAdapter.history} root to the bundle root it
 * denotes, so equivalent spellings of the same root canonicalize identically (LORE-243): a leading
 * `./`, a trailing `/.`, and internal redundant separators (`//`, `/./`) are all collapsed via
 * {@link posix.normalize} before the trailing slash(es) are stripped — so `./docs`, `docs/.`,
 * `./docs/`, and `docs//adr`/`docs/./adr` all resolve exactly like `docs`/`docs/adr`. Without the
 * `posix.normalize` pass, the `${root}/` probe in {@link isUnderRoot} would compare against the
 * un-normalized root and match nothing — a silently empty log. Falls back to {@link DOCS_DIR} for an
 * absent, empty, or all-slashes root (`normalize` reduces those to `"."` or `"/"`, neither of which
 * would match anything as a bundle root). Shared by {@link generateLog} (post-filtering) and
 * {@link buildLog} (the pathspec handed to {@link GitAdapter.history}) so the two always agree on
 * exactly which root scopes a given `log.md`.
 */
function resolveRoot(root: string | undefined): string {
  const normalized = posix.normalize(root || DOCS_DIR).replace(/\/+$/, "");
  return normalized === "" || normalized === "." ? DOCS_DIR : normalized;
}

/**
 * The distinct bundle folders a commit's `files` touch, scoped to `root`. A folder is the immediate
 * parent directory of a touched file (`docs/adr/0014.md` → `docs/adr`). A file directly under the
 * root (`docs/index.md` → `docs`) groups under the root itself. Files outside the root are dropped.
 * {@link generateLog} assigns the commit to this set's deepest common folder.
 */
function foldersTouched(files: readonly string[], root: string): Set<string> {
  const folders = new Set<string>();
  for (const file of files) {
    if (isUnderRoot(file, root)) {
      folders.add(posix.dirname(file));
    }
  }
  return folders;
}

/** The deepest shared POSIX directory of `folders`, or undefined when it is empty. */
function commonFolder(folders: ReadonlySet<string>): string | undefined {
  const [first, ...rest] = folders;
  if (first === undefined) {
    return undefined;
  }

  const shared = first.split("/");
  for (const folder of rest) {
    const segments = folder.split("/");
    let length = 0;
    while (length < shared.length && shared[length] === segments[length]) {
      length += 1;
    }
    shared.length = length;
  }
  return shared.join("/");
}

/**
 * True when `file` sits **strictly under** the bundle root (`<root>/…`). A file whose path *equals*
 * the root is deliberately excluded: it is a file literally named `docs` (not a bundle document), and
 * `posix.dirname` would put it under the root's *parent* (`.`), emitting a section above the bundle.
 * A document directly under the root — `docs/index.md` — still matches and groups under `## docs`.
 */
function isUnderRoot(file: string, root: string): boolean {
  return file.startsWith(`${root}/`);
}

/** Matches the offset suffix of an ISO-8601 timestamp — `Z`, or `±HH:MM`/`±HHMM` (colon optional). */
const ISO_OFFSET = /(?:Z|[+-]\d{2}:?\d{2})$/;

/**
 * The absolute instant `timestamp` denotes, in epoch milliseconds, or `NaN` when it does not denote
 * one. Only an **offset-bearing** ISO-8601 timestamp (the {@link GitCommit.timestamp} contract) is a
 * fixed instant; an offset-*less* one would be parsed in the host's local time zone — a
 * machine-dependent result that has no place in byte-stable output — so it is reported as `NaN` and
 * left to the deterministic text tiebreak, never trusted as a number.
 */
function toInstant(timestamp: string): number {
  return ISO_OFFSET.test(timestamp) ? Date.parse(timestamp) : Number.NaN;
}

/**
 * Order entries by ascending absolute **instant**, then by deterministic, machine-independent
 * tiebreaks. Timestamps are ISO-8601 *with offset* (see {@link GitCommit.timestamp}), so two equal
 * instants written in different offsets compare equal — a lexical compare would order them by
 * wall-clock text instead. Each entry's instant is precomputed ({@link LogEntry.instant}); when both
 * are real instants they order numerically, and an entry with a real instant always precedes one
 * without (an offset-less/unparseable timestamp). On an exact instant tie — or when neither has an
 * instant — the order falls through to `(timestamp, hash, subject)` code-unit compares, so it stays
 * **total and reproducible** (the subject tiebreak keeps two commits sharing an instant *and* an
 * abbreviated hash from falling back to input order).
 */
function compareEntries(a: LogEntry, b: LogEntry): number {
  const aHasInstant = !Number.isNaN(a.instant);
  const bHasInstant = !Number.isNaN(b.instant);
  if (aHasInstant && bHasInstant) {
    if (a.instant !== b.instant) {
      return a.instant < b.instant ? -1 : 1;
    }
  } else if (aHasInstant !== bHasInstant) {
    return aHasInstant ? -1 : 1;
  }
  return (
    compareCodeUnits(a.timestamp, b.timestamp) ||
    compareCodeUnits(a.hash, b.hash) ||
    compareCodeUnits(a.subject, b.subject)
  );
}
