/**
 * rewrite.ts — the **pure** graph-aware inbound-rewrite engine behind `lore rename` (and,
 * next, `lore supersede`): when a concept's id/path changes, repoint **every** reference to
 * it — body cross-links and `specs`/`supersedes`/`superseded_by` frontmatter refs — to the new
 * location, without touching one byte of authored prose (cli-surface §rename, LORE-35 AC#1–3).
 *
 * ### Why a surgical string splice, not parse→stringify
 *
 * lore deliberately ships **no markdown serializer** (deps are only `mdast-util-from-markdown`
 * for parsing, plus gray-matter/js-yaml/zod for frontmatter — ADR-0001 packaging constraint).
 * Re-emitting a body through a stringifier would reflow prose — reindenting lists, normalizing
 * emphasis, rewrapping — which ADR-0008 §7 forbids and AC#3 pins against. So a link's
 * destination is rewritten by **splicing the new bytes over the old destination's byte range**,
 * located structurally inside the parsed link node; every other byte of the body is copied
 * verbatim.
 *
 * Locating that range cannot use a text search for the destination, because a parsed
 * `node.url` is **not** byte-equal to the source it came from: `mdast-util-from-markdown`
 * strips an angle-bracket `<…>` wrapper, decodes backslash escapes (`a\(b\).md` → `a(b).md`),
 * and drops an optional `"title"` — while *keeping* percent-encoding. An `indexOf(node.url)`
 * would miss (or, worse, mis-hit) the destination. Instead {@link destRangeForLink} /
 * {@link destRangeForDefinition} walk the source from the link node's known start offset to find
 * the exact `[start, end)` of the destination token as authored (see each for the grammar).
 *
 * ### What gets rewritten
 *
 * The affected files are computed from the graph, not a directory scan: the moved concept itself
 * (when `move`), plus every concept that is the `from` of an edge whose `to` is the renamed
 * concept (any {@link EdgeKind}). For each affected concept:
 *
 * - **Inbound files** (point *at* the renamed concept): each body link or used reference
 *   definition that resolves to `fromId` is repointed to the new path via {@link normalizeLink}
 *   (preserving any `#fragment`/`?query`); each `specs`/`supersedes`/`superseded_by` ref that
 *   resolves to `fromId` is rewritten to the bare-id `toId` (the canonical frontmatter ref form).
 * - **The moved file** (only when `move`): *all* of its outbound internal links are recomputed
 *   against its new directory — they move with the file — so a sibling link becomes a `../`
 *   link (or vice versa) and a self-link retargets to the new name. This is pure path
 *   arithmetic, so it corrects even links that dangle (resolve to no concept).
 *
 * Resolution mirrors the bundle graph's own rules byte-for-byte ({@link bundle}'s
 * `internalTarget` + path-join + {@link idFromPath}, and `resolveRef` for frontmatter), so this
 * engine rewrites exactly the edges the graph counts — case-sensitively, leading-slash absorbed,
 * no `/`-absolute special case (unlike `lore check`'s portability view).
 *
 * The rewritten bytes are produced by {@link serializeConcept} (frontmatter in canonical,
 * byte-stable form; body verbatim with the splices applied), so an already-canonical concept's
 * frontmatter round-trips unchanged and only its changed destinations/refs differ.
 *
 * ### Boundaries (deliberate, documented)
 *
 * - Only **concept** files are rewritten — a graph edge always originates at a concept. A link
 *   to the renamed concept from a *non-concept* markdown file (a frontmatter-free `index.md`
 *   listing's authored prose, a README) is not a graph edge and is left for `lore check` to
 *   surface; the machine-owned `index.md` listing blocks are regenerated by the command layer
 *   via {@link generateIndexes}, not here.
 * - The moved file's own outbound references are recomputed for its new location — body links by
 *   path arithmetic, and resolving frontmatter refs canonicalized to their bare (location-
 *   independent) id. A frontmatter ref that *dangles* (resolves to no concept) is left as-is, the
 *   same broken signal `lore check` already reports.
 *
 * Per the core contract (lore-design §2.1) everything here is pure: a {@link BundleGraph} in, a
 * {@link RewritePlan} out, or a `not_found`/`conflict` {@link LoreError}. No filesystem, no
 * printing, no flags, no `process.exit` — the command layer reads the bundle, writes the plan's
 * bytes, and performs the move/delete.
 */

import { posix, win32 } from "node:path";
import type { Nodes } from "mdast";
import { fromMarkdown } from "mdast-util-from-markdown";
import { LoreError } from "../errors";
import {
  type BundleGraph,
  conceptNotInBundle,
  internalTarget,
  REF_FIELDS,
  resolvePath,
  resolveRef,
  walkMdast,
} from "./bundle";
import { type Concept, idFromPath, serializeConcept } from "./concept";
import { normalizeLink } from "./links";
import { compareCodeUnits } from "./order";
import { DOCS_DIR } from "./scaffold";

/** A half-open `[start, end)` byte range within a body, locating a link destination to splice. */
interface ByteRange {
  readonly start: number;
  readonly end: number;
}

/** One file the plan writes: its bundle-relative path and the new bytes (full file contents). */
export interface RewriteWrite {
  /** Bundle-relative path of the file to write (the moved file carries its **new** path). */
  readonly path: string;
  /** The complete new file contents. */
  readonly bytes: string;
}

/**
 * The result of {@link rewriteInbound}: the optional file move and every file whose bytes change.
 * `rename` is non-null only in `move` mode — it tells the command which file to write at the new
 * path and delete at the old; the moved file's new bytes are in `writes` under its new path.
 * `writes` is in ascending-path order for a stable, reviewable plan.
 */
export interface RewritePlan {
  /** The file relocation (`move` mode only): write `to`, delete `from`. `null` in place-only mode. */
  readonly rename: { readonly from: string; readonly to: string } | null;
  /** Each changed file's new bytes, ascending by path. */
  readonly writes: readonly RewriteWrite[];
}

/** Options for {@link rewriteInbound}. */
export interface RewriteInboundOptions {
  /**
   * Whether the renamed concept **relocates** (`lore rename`): its file moves `fromId`→`toId`,
   * its own outbound links are recomputed, and `toId` must not already exist. When `false`
   * (`lore supersede`'s `--rewrite-links`), nothing moves — only inbound references are
   * repointed — and `toId` is expected to already exist (the command validates that).
   */
  readonly move?: boolean;
  /**
   * Whether to repoint `specs`/`supersedes`/`superseded_by` **frontmatter** refs as well as body
   * links. Defaults to `true` (`lore rename`: the old path vanishes, so every ref to it — structured
   * or prose — must move or dangle). `lore supersede` passes `false`: it **preserves** the old file,
   * so a third party's `supersedes`/`superseded_by`/`specs` ref to it is still a valid historical
   * record, not a dead pointer — repointing it would fabricate a relationship that never happened.
   * Only body cross-links (the navigational "go read this" edges) are redirected to the successor.
   */
  readonly rewriteFrontmatterRefs?: boolean;
  /**
   * Concept ids the caller will rewrite itself and the engine must therefore leave untouched (never
   * parsed, serialized, or emitted in the plan). `lore supersede` excludes the two **principals**
   * (it wires their frontmatter directly — repointing the successor's own link to its predecessor,
   * or the preserved old doc's self-link, would be wrong) and the machine-owned `index.md`/`log.md`
   * hubs (regenerated by `lore sync`, never hand-rewritten). Empty by default (`lore rename` rewrites
   * everything its graph reaches).
   */
  readonly exclude?: ReadonlySet<string>;
}

/** The shared empty exclude set, so the common (no-exclude) path allocates nothing. */
const NO_EXCLUDE: ReadonlySet<string> = new Set();

/**
 * Compute the {@link RewritePlan} to repoint every reference to `fromId` onto `toId`.
 *
 * In `move` mode (`lore rename`) the concept relocates: `fromId` must exist, `toId` must not,
 * inbound references are repointed, and the moved file's own outbound links are recomputed for
 * its new directory. Without `move` (`lore supersede`) the concept stays put and only inbound
 * references are repointed.
 *
 * @throws LoreError `not_found` when `fromId` names no concept; `conflict` (move mode) when
 *   `toId` already names a concept.
 */
export function rewriteInbound(
  graph: BundleGraph,
  fromId: string,
  toId: string,
  options: RewriteInboundOptions = {},
): RewritePlan {
  const move = options.move ?? false;
  const rewriteRefs = options.rewriteFrontmatterRefs ?? true;
  const exclude = options.exclude ?? NO_EXCLUDE;
  assertConfinedToBundle(fromId, "fromId");
  assertConfinedToBundle(toId, "toId");
  const from = idFromPath(fromId);
  const to = idFromPath(toId);

  const fromConcept = graph.concepts.get(from);
  if (fromConcept === undefined) {
    throw conceptNotInBundle(from);
  }
  if (move && graph.concepts.has(to)) {
    throw new LoreError(
      "conflict",
      `cannot rename to "${to}": a concept already exists there`,
      "choose an id/path that is not already taken, or supersede instead of rename",
      { id: to },
    );
  }

  const fromPath = fromConcept.path;
  const toPath = `${to}.md`;

  // Affected files: the moved concept (always, in move mode) plus every concept with an edge
  // pointing at it. A Set folds a file that both moves and self-references into one rewrite.
  const affected = new Set<string>();
  if (move) {
    affected.add(from);
  }
  for (const edge of graph.edges) {
    if (edge.to === from) {
      affected.add(edge.from);
    }
  }

  const writes: RewriteWrite[] = [];
  for (const id of affected) {
    if (exclude.has(id)) {
      continue; // the caller rewrites this file itself — never parse, serialize, or plan it here
    }
    const concept = graph.concepts.get(id);
    if (concept === undefined) {
      continue; // an edge's `from` is always a real concept; this is unreachable belt-and-braces
    }
    const isMoved = move && id === from;
    const rewritten = rewriteConcept(concept, graph, { from, to, fromPath, toPath, isMoved, rewriteRefs });
    if (rewritten === null && !isMoved) {
      continue; // nothing changed in this file and it does not move — leave it untouched
    }
    const bytes = rewritten ?? serializeConcept(concept);
    writes.push({ path: isMoved ? toPath : concept.path, bytes });
  }

  writes.sort((a, b) => compareCodeUnits(a.path, b.path));
  return { rename: move ? { from: fromPath, to: toPath } : null, writes };
}

/**
 * Reject a `fromId`/`toId` that would resolve outside the `docs/` bundle root — closes the
 * traversal gap for every {@link rewriteInbound} caller (`lore rename`, `lore supersede`) at the
 * one shared layer both funnel through (LORE-80). Checked on the RAW caller-supplied value,
 * before {@link idFromPath} ever runs.
 *
 * An absolute path is checked against BOTH `posix.isAbsolute` and `win32.isAbsolute` — this ships
 * as a compiled binary for both platforms from the same source, so a Windows drive-letter id
 * (inert POSIX-side, genuinely absolute on a win32 run) must be rejected regardless of which
 * platform is running (the LORE-69 cross-platform-normalize convention).
 *
 * A relative escape is caught by {@link escapesRoot}, which walks segments split on EITHER `/` or
 * `\` — not just `posix.normalize`'s own forward-slash-only splitting. `idFromPath`'s
 * `posix.normalize` treats a backslash as an ordinary filename character, not a separator, so a
 * relative traversal spelled `..\pwned` survives it completely unchanged and would trip neither
 * `posix.isAbsolute` (it isn't) nor `win32.isAbsolute` (it's relative, not absolute — that check
 * only matches a drive-letter/UNC/leading-separator *absolute* form). Yet the command layer's
 * eventual write (`commands/rename.ts`, via the platform-native `path.join`) treats `\` as a
 * separator on an actual Windows run, so `..\pwned` is exactly as real an escape there as
 * `../pwned` is everywhere else — this check must catch it on every platform it runs on, not only
 * the one it happens to be compiled for.
 */
function assertConfinedToBundle(id: string, label: "fromId" | "toId"): void {
  if (posix.isAbsolute(id) || win32.isAbsolute(id) || escapesRoot(id)) {
    throw new LoreError(
      "validation",
      `${label} "${id}" resolves outside the docs/ bundle root`,
      "pass an id that stays inside the docs/ bundle",
      { id },
    );
  }
}

/**
 * Whether walking `id`'s segments — split on a run of either `/` or `\`, since either can act as
 * a separator depending on which platform's binary eventually resolves it (see
 * {@link assertConfinedToBundle}) — climbs above the directory `id` starts in. A literal `..`
 * segment always means "parent directory": no real filesystem, on either platform, permits a
 * file or directory literally named `..`, so this can never misfire on a genuine bundle id — nor
 * reject a real segment that merely *starts* with `..` (e.g. `..foo/bar`), since that segment
 * does not equal `..` exactly (mirrors `new.ts`'s `resolveOutPath`'s own documented care).
 *
 * Exported so a command layer can reuse this exact, already-review-tested traversal check for its
 * own defense-in-depth confinement guard (e.g. `commands/rename.ts`'s `newId`, LORE-79) instead of
 * re-deriving the same security-sensitive segment walk a second time.
 */
export function escapesRoot(id: string): boolean {
  let depth = 0;
  for (const segment of id.split(/[\\/]+/)) {
    if (segment === "" || segment === ".") {
      continue;
    }
    if (segment === "..") {
      if (depth === 0) {
        return true;
      }
      depth--;
    } else {
      depth++;
    }
  }
  return false;
}

/** The resolved coordinates one concept's rewrite needs (`from`/`to` are normalized ids). */
interface RewriteContext {
  readonly from: string;
  readonly to: string;
  readonly fromPath: string;
  readonly toPath: string;
  /** Whether this concept is the relocating one (recompute all its outbound links). */
  readonly isMoved: boolean;
  /** Whether to repoint `specs`/`supersedes`/`superseded_by` frontmatter refs (false for `lore supersede`). */
  readonly rewriteRefs: boolean;
}

/**
 * Rewrite one affected concept, returning its new serialized bytes, or `null` when nothing in it
 * changed (no body destination and no frontmatter ref needed rewriting). The moved file always
 * yields bytes from its caller even on a `null` here, because it still relocates.
 */
function rewriteConcept(concept: Concept, graph: BundleGraph, ctx: RewriteContext): string | null {
  const dir = posix.dirname(concept.path);
  const edits = computeBodyEdits(concept.body, concept.path, ctx);
  const newBody = applyBodyEdits(concept.body, edits);

  // `lore supersede` (rewriteRefs=false) preserves the old file, so a third party's frontmatter ref
  // to it stays a valid historical record — only body links are redirected to the successor.
  const newFrontmatter = ctx.rewriteRefs ? remapFrontmatterRefs(concept.frontmatter, dir, graph, ctx) : null;
  const frontmatterChanged = newFrontmatter !== null;

  if (newBody === concept.body && !frontmatterChanged) {
    return null;
  }
  const next: Concept = {
    ...concept,
    frontmatter: frontmatterChanged ? newFrontmatter : concept.frontmatter,
    body: newBody,
  };
  return serializeConcept(next);
}

// ── Body link rewriting ──────────────────────────────────────────────────────────

/** A planned destination splice: the source byte range to replace and its replacement text. */
interface BodyEdit extends ByteRange {
  readonly dest: string;
}

/**
 * Compute every destination splice for one concept body. The body is parsed once; each inline
 * link and each *used* reference definition (a definition an actual `linkReference` points at,
 * mirroring how the bundle graph counts edges — an orphan definition is not an edge) is a
 * candidate. For the moved file, every internal link is recomputed against the new directory; for
 * an inbound file, only links that resolve to `fromId` are repointed. An edit is emitted only when
 * the new destination differs from the authored bytes, so a canonical link the move leaves in
 * place produces no churn.
 */
function computeBodyEdits(body: string, conceptPath: string, ctx: RewriteContext): BodyEdit[] {
  const tree = fromMarkdown(body);
  const links: Nodes[] = [];
  const usedIdentifiers = new Set<string>();
  const firstDefinition = new Map<string, Nodes>();
  const allDefinitions: Nodes[] = [];
  walkMdast(tree, (node) => {
    if (node.type === "link") {
      links.push(node);
    } else if (node.type === "linkReference") {
      usedIdentifiers.add(node.identifier);
    } else if (node.type === "definition") {
      allDefinitions.push(node);
      if (!firstDefinition.has(node.identifier)) {
        firstDefinition.set(node.identifier, node); // first definition wins, as CommonMark resolves
      }
    }
  });

  // Candidate destinations in document order: inline links, then reference definitions. For the
  // moved file *every* definition is recomputed (it moves with the file, even an orphan/unused one
  // that renders as nothing); for an inbound file only the **used** definitions are edges, so an
  // orphan definition is left alone — mirroring how the bundle graph counts edges.
  const candidates: Array<{ node: Nodes; isDefinition: boolean }> = links.map((node) => ({
    node,
    isDefinition: false,
  }));
  if (ctx.isMoved) {
    for (const def of allDefinitions) {
      candidates.push({ node: def, isDefinition: true });
    }
  } else {
    for (const identifier of usedIdentifiers) {
      const def = firstDefinition.get(identifier);
      if (def !== undefined) {
        candidates.push({ node: def, isDefinition: true });
      }
    }
  }

  const edits: BodyEdit[] = [];
  for (const { node, isDefinition } of candidates) {
    const newPath = newDestPathFor((node as { url: string }).url, conceptPath, ctx);
    if (newPath === null) {
      continue; // external/non-.md, or (inbound) not a link to the renamed concept
    }
    const range = isDefinition ? destRangeForDefinition(body, node) : destRangeForLink(body, node);
    if (range === null) {
      continue; // defensive: a well-formed link/definition always locates, but never corrupt on a miss
    }
    // Append the destination's #fragment/?query taken from the **source** bytes (not the decoded
    // node.url), so an authored fragment — even one carrying escapes — is preserved byte-for-byte
    // (AC#3); only the path portion is replaced with the canonical form.
    const src = body.slice(range.start, range.end);
    const newDest = newPath + sourceSuffix(src);
    if (src === newDest) {
      continue; // already the canonical bytes — no edit (the move left this link in place)
    }
    edits.push({ start: range.start, end: range.end, dest: newDest });
  }
  return edits;
}

/**
 * The canonical **path** (no `#fragment`/`?query`) one link should point at after the rename, or
 * `null` when the link is not a target: external, non-`.md`, or — for an inbound file — not a link
 * to the renamed concept. Classification and id derivation reuse the bundle graph's own
 * {@link internalTarget}/{@link resolvePath}, so it rewrites exactly the edges the graph counts.
 */
function newDestPathFor(url: string, conceptPath: string, ctx: RewriteContext): string | null {
  const decoded = internalTarget(url);
  if (decoded === null) {
    return null; // external, anchor-only, or non-.md — not an internal concept link
  }
  const dir = posix.dirname(conceptPath);
  const targetId = idFromPath(posix.join(dir, decoded));

  // normalizeLink's precondition is the repo-relative coordinate space (both operands rooted at
  // the repo, `docs/…`), not the bundle-relative one `conceptPath`/`ctx.to` use as graph ids. The
  // two coincide for a link that stays inside the bundle (a constant `docs/` prefix cancels out of
  // a relative-path computation), which is why this only ever surfaced for a link that escapes the
  // bundle root — e.g. a Story's managed task block linking `backlog/tasks/…` (LORE-68): resolving
  // `decoded`/`ctx.toPath` in bundle-relative space silently drops the `docs/` hop, truncating the
  // rewritten link by one `../` segment.
  const repoDir = `${DOCS_DIR}/${dir}`;
  const repoToPath = `${DOCS_DIR}/${ctx.toPath}`;

  if (ctx.isMoved) {
    // The file moves: recompute the link against its new directory. A self-link follows the file
    // to its new path; any other target keeps its location (pure path arithmetic, so a dangling
    // link is corrected too).
    const targetPath = targetId === ctx.from ? repoToPath : posix.normalize(posix.join(repoDir, decoded));
    return normalizeLink(repoToPath, targetPath);
  }
  if (targetId !== ctx.from) {
    return null; // an inbound file only repoints links to the renamed concept
  }
  // An inbound link is recomputed from *this* file's location to the moved concept's new path.
  return normalizeLink(`${DOCS_DIR}/${conceptPath}`, repoToPath);
}

/**
 * The `#fragment`/`?query` suffix of a source destination token, preserved verbatim: the
 * angle-bracket `<…>` wrapper (which the canonical form drops) is stripped, then everything from
 * the first `#`/`?` onward is returned — the authored bytes, never the decoded `node.url`.
 */
function sourceSuffix(src: string): string {
  const inner = src.startsWith("<") && src.endsWith(">") ? src.slice(1, -1) : src;
  const hash = inner.indexOf("#");
  const question = inner.indexOf("?");
  // The first of the two delimiters that is present (a `?` living inside a `#fragment` is not a query).
  const cut = hash < 0 ? question : question < 0 ? hash : Math.min(hash, question);
  return cut < 0 ? "" : inner.slice(cut);
}

/** Apply destination splices right-to-left (descending start) so earlier edits don't shift later offsets. */
function applyBodyEdits(body: string, edits: BodyEdit[]): string {
  if (edits.length === 0) {
    return body;
  }
  const ordered = [...edits].sort((a, b) => b.start - a.start);
  let result = body;
  for (const edit of ordered) {
    result = result.slice(0, edit.start) + edit.dest + result.slice(edit.end);
  }
  return result;
}

// ── Destination range location (structural, not a text search) ─────────────────────

/**
 * The `[start, end)` byte range of an **inline** link's destination token (`[label](DEST)` or
 * `[label](<DEST>)`, with an optional `"title"` after `DEST`), located structurally from the
 * link node's offsets — because `node.url` is not byte-equal to the source (see the module
 * header). Returns the full token including a `<…>` wrapper (so it is replaced by the canonical,
 * wrapper-free form) and any `#fragment`/`?query`, but excludes a following `"title"`. `null` if
 * the structure cannot be located (never expected for a parsed link).
 */
function destRangeForLink(body: string, node: Nodes): ByteRange | null {
  const span = positionOf(node);
  if (span === null) {
    return null;
  }
  // End of the label content: the last child's end offset, or just past `[` for an empty label.
  const contentEnd = maxChildEnd(node) ?? span.start + 1;
  const rb = body.indexOf("]", contentEnd); // the label's closing `]`
  if (rb === -1 || body[rb + 1] !== "(") {
    return null;
  }
  return scanDestination(body, rb + 2, span.end, true);
}

/**
 * The `[start, end)` byte range of a **reference definition**'s destination (`[label]: DEST
 * "title"`), located structurally from the node's offsets. Unlike an inline link, the raw form
 * has no enclosing `()`, so the destination ends at whitespace (a following title) or the node's
 * end — not at a closing paren. `null` if the structure cannot be located.
 *
 * Unlike {@link destRangeForLink}, a `definition` node carries no parsed `children` to derive the
 * label's end from structurally (mdast gives only its decoded `identifier`/`label` strings, whose
 * lengths are not byte-equal to the raw source once escapes are involved — the same reason
 * `node.url` can't drive a text search, see the module header) — so the closing `]` is located by
 * an escape-aware raw scan ({@link findLabelClose}) instead of a plain `indexOf`, which would
 * match an escaped `\]` *inside* the label rather than the real closing bracket (LORE-87).
 */
function destRangeForDefinition(body: string, node: Nodes): ByteRange | null {
  const span = positionOf(node);
  if (span === null) {
    return null;
  }
  const rb = findLabelClose(body, span.start + 1, span.end); // the label's closing `]`
  if (rb === -1) {
    return null;
  }
  const colon = body.indexOf(":", rb);
  if (colon === -1) {
    return null;
  }
  return scanDestination(body, colon + 1, span.end, false);
}

/**
 * The index of a reference definition's label-closing `]`, scanned from just after the opening
 * `[` (`from`) and honoring `\` escapes — the same escape convention {@link scanDestination}
 * applies to a destination, so `\]` inside the label is skipped rather than mistaken for the real
 * closing bracket (LORE-87). `-1` if none is found before `end`.
 */
function findLabelClose(body: string, from: number, end: number): number {
  let j = from;
  while (j < end) {
    if (body[j] === "\\") {
      j += 2;
      continue;
    }
    if (body[j] === "]") {
      return j;
    }
    j++;
  }
  return -1;
}

/**
 * Scan a link destination starting at `from` (just after `(` for an inline link, or after `:`
 * for a definition), bounded by `end` (the node's end offset). Leading whitespace is skipped;
 * then either an angle-bracket `<…>` form (scanned to its closing `>`, honoring `\` escapes) or
 * a raw form (honoring `\` escapes and — for an inline link — balanced `()`, stopping at
 * unescaped whitespace before a title, or at the inline link's closing `)`). `inline` selects
 * whether an unescaped depth-0 `)` ends the destination.
 */
function scanDestination(body: string, from: number, end: number, inline: boolean): ByteRange | null {
  let i = from;
  while (i < end && isWhitespace(body[i])) {
    i++;
  }
  if (i >= end) {
    return null;
  }
  const start = i;
  if (body[i] === "<") {
    let j = i + 1;
    while (j < end && body[j] !== ">") {
      j += body[j] === "\\" ? 2 : 1;
    }
    return { start, end: Math.min(j + 1, end) }; // include the closing `>`
  }
  let depth = 0;
  let j = i;
  while (j < end) {
    const c = body[j];
    if (c === "\\") {
      j += 2;
      continue;
    }
    if (isWhitespace(c)) {
      break; // a title (or nothing) follows
    }
    if (c === "(") {
      depth++;
    } else if (c === ")") {
      if (inline && depth === 0) {
        break; // the inline link's closing `)`
      }
      if (depth > 0) {
        depth--;
      }
    }
    j++;
  }
  return { start, end: Math.min(j, end) };
}

/** Whether `c` is ASCII whitespace that bounds a link destination (space, tab, newline, CR, FF). */
function isWhitespace(c: string | undefined): boolean {
  return c === " " || c === "\t" || c === "\n" || c === "\r" || c === "\f";
}

/** The max end offset among a node's direct children, or `null` when it has none (an empty label). */
function maxChildEnd(node: Nodes): number | null {
  if (!("children" in node) || node.children.length === 0) {
    return null;
  }
  let max = 0;
  let seen = false;
  for (const child of node.children) {
    const span = positionOf(child);
    if (span !== null) {
      max = Math.max(max, span.end);
      seen = true;
    }
  }
  return seen ? max : null;
}

/** A node's `[start, end)` source offsets, or `null` when position info is absent (defensive). */
function positionOf(node: Nodes): ByteRange | null {
  const position = node.position;
  if (position?.start.offset === undefined || position.end.offset === undefined) {
    return null;
  }
  return { start: position.start.offset, end: position.end.offset };
}

// ── Frontmatter ref rewriting ──────────────────────────────────────────────────────

/**
 * Return a new frontmatter object with the `specs`/`supersedes`/`superseded_by` refs rewritten, or
 * `null` when none changed. A field may be a single ref or a list — both shapes are preserved, and
 * a non-matching item (including a non-string producer value) is copied verbatim. The original
 * object is never mutated (the graph snapshot stays intact). The ref fields iterated are the
 * graph's own {@link REF_FIELDS}, so a future ref kind cannot be added as an edge without also
 * being rewritten here.
 */
function remapFrontmatterRefs(
  frontmatter: Record<string, unknown>,
  dir: string,
  graph: BundleGraph,
  ctx: RewriteContext,
): Record<string, unknown> | null {
  let changed = false;
  const next: Record<string, unknown> = { ...frontmatter };
  for (const field of REF_FIELDS) {
    const value = frontmatter[field];
    if (value === undefined) {
      continue;
    }
    if (Array.isArray(value)) {
      const mapped = value.map((item) => remapRefItem(item, dir, graph, ctx));
      if (mapped.some((item, i) => item !== value[i])) {
        next[field] = mapped;
        changed = true;
      }
    } else {
      const mapped = remapRefItem(value, dir, graph, ctx);
      if (mapped !== value) {
        next[field] = mapped;
        changed = true;
      }
    }
  }
  return changed ? next : null;
}

/**
 * Rewrite one frontmatter ref item, reusing the bundle graph's own {@link resolveRef} (which trims
 * and classifies exactly as the edge collector does, so this repoints exactly the refs the graph
 * counts). A non-string or a dangling ref is returned unchanged. For an **inbound** file only a ref
 * that resolves to the renamed concept is rewritten (to the bare-id `to`). For the **moved** file
 * every resolving ref is canonicalized to its bare id — which both repoints a self-ref to `to` and
 * corrects a relative-path ref to *another* concept that the move would otherwise leave pointing at
 * the wrong location (the body-link recompute does the analogous fix); an already-bare-id ref maps
 * to itself, so it is left byte-identical.
 */
function remapRefItem(item: unknown, dir: string, graph: BundleGraph, ctx: RewriteContext): unknown {
  if (typeof item !== "string") {
    return item;
  }
  const resolved = resolveRef(item, dir, graph.concepts);
  if (resolved === null) {
    return item; // external or dangling — not a concept ref to repoint
  }
  if (!ctx.isMoved) {
    return resolved === ctx.from ? ctx.to : item;
  }
  return resolved === ctx.from ? ctx.to : resolved; // moved file: canonicalize to bare id
}
